//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "basicTagsBackgroundTypeSettings1"
	/// <summary>[Nubrik][Style][Theme Settings][Basic] [Button] Background Type</summary>
	public partial interface IBasicTagsBackgroundTypeSettings1 : IPublishedElement
	{
		/// <summary>Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicButtonBackgroundColor { get; }

		/// <summary>Gradient Angle (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicButtonBackgroundGradientAngleDesktop { get; }

		/// <summary>Gradient Angle (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicButtonBackgroundGradientAngleMobile { get; }

		/// <summary>Gradient Angle (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicButtonBackgroundGradientAngleTablet { get; }

		/// <summary>Gradient Primary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicButtonBackgroundGradientPrimaryColor { get; }

		/// <summary>Primary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicButtonBackgroundGradientPrimaryLocationDesktop { get; }

		/// <summary>Primary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicButtonBackgroundGradientPrimaryLocationMobile { get; }

		/// <summary>Primary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicButtonBackgroundGradientPrimaryLocationTablet { get; }

		/// <summary>Gradient Secondary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicButtonBackgroundGradientSecondaryColor { get; }

		/// <summary>Secondary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicButtonBackgroundGradientSecondaryLocationDesktop { get; }

		/// <summary>Secondary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicButtonBackgroundGradientSecondaryLocationMobile { get; }

		/// <summary>Secondary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicButtonBackgroundGradientSecondaryLocationTablet { get; }

		/// <summary>Gradient Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicButtonBackgroundGradientType { get; }

		/// <summary>Background Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicButtonBackgroundType { get; }

		/// <summary>Background Type - Classic (Label)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string NuignorebasicButtonBackgroundTypeClassic { get; }

		/// <summary>Background Type - Gradient (Label)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string NuignorebasicButtonBackgroundTypeGradient { get; }
	}

	/// <summary>[Nubrik][Style][Theme Settings][Basic] [Button] Background Type</summary>
	[PublishedModel("basicTagsBackgroundTypeSettings1")]
	public partial class BasicTagsBackgroundTypeSettings1 : PublishedElementModel, IBasicTagsBackgroundTypeSettings1
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "basicTagsBackgroundTypeSettings1";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<BasicTagsBackgroundTypeSettings1, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public BasicTagsBackgroundTypeSettings1(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Background Color: Select the background color for the button.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicButtonBackgroundColor")]
		public virtual string BasicButtonBackgroundColor => GetBasicButtonBackgroundColor(this, _publishedValueFallback);

		/// <summary>Static getter for Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicButtonBackgroundColor(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicButtonBackgroundColor");

		///<summary>
		/// Gradient Angle (Desktop): Specify the gradient angle for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicButtonBackgroundGradientAngleDesktop")]
		public virtual string BasicButtonBackgroundGradientAngleDesktop => GetBasicButtonBackgroundGradientAngleDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Gradient Angle (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicButtonBackgroundGradientAngleDesktop(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicButtonBackgroundGradientAngleDesktop");

		///<summary>
		/// Gradient Angle (Mobile): Specify the gradient angle for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicButtonBackgroundGradientAngleMobile")]
		public virtual string BasicButtonBackgroundGradientAngleMobile => GetBasicButtonBackgroundGradientAngleMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Gradient Angle (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicButtonBackgroundGradientAngleMobile(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicButtonBackgroundGradientAngleMobile");

		///<summary>
		/// Gradient Angle (Tablet): Specify the gradient angle for tablet devices
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicButtonBackgroundGradientAngleTablet")]
		public virtual string BasicButtonBackgroundGradientAngleTablet => GetBasicButtonBackgroundGradientAngleTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Gradient Angle (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicButtonBackgroundGradientAngleTablet(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicButtonBackgroundGradientAngleTablet");

		///<summary>
		/// Gradient Primary Color: Select the primary color used in the background gradient.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicButtonBackgroundGradientPrimaryColor")]
		public virtual string BasicButtonBackgroundGradientPrimaryColor => GetBasicButtonBackgroundGradientPrimaryColor(this, _publishedValueFallback);

		/// <summary>Static getter for Gradient Primary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicButtonBackgroundGradientPrimaryColor(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicButtonBackgroundGradientPrimaryColor");

		///<summary>
		/// Primary Color Position (Desktop): Specify the position of the primary gradient color stop for desktop devices (0-100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicButtonBackgroundGradientPrimaryLocationDesktop")]
		public virtual string BasicButtonBackgroundGradientPrimaryLocationDesktop => GetBasicButtonBackgroundGradientPrimaryLocationDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Primary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicButtonBackgroundGradientPrimaryLocationDesktop(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicButtonBackgroundGradientPrimaryLocationDesktop");

		///<summary>
		/// Primary Color Position (Mobile): Specify the position of the primary gradient color stop for mobile devices (0-100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicButtonBackgroundGradientPrimaryLocationMobile")]
		public virtual string BasicButtonBackgroundGradientPrimaryLocationMobile => GetBasicButtonBackgroundGradientPrimaryLocationMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Primary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicButtonBackgroundGradientPrimaryLocationMobile(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicButtonBackgroundGradientPrimaryLocationMobile");

		///<summary>
		/// Primary Color Position (Tablet): Specify the position of the primary gradient color stop for tablet devices (0-100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicButtonBackgroundGradientPrimaryLocationTablet")]
		public virtual string BasicButtonBackgroundGradientPrimaryLocationTablet => GetBasicButtonBackgroundGradientPrimaryLocationTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Primary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicButtonBackgroundGradientPrimaryLocationTablet(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicButtonBackgroundGradientPrimaryLocationTablet");

		///<summary>
		/// Gradient Secondary Color: Select the secondary color used in the background gradient.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicButtonBackgroundGradientSecondaryColor")]
		public virtual string BasicButtonBackgroundGradientSecondaryColor => GetBasicButtonBackgroundGradientSecondaryColor(this, _publishedValueFallback);

		/// <summary>Static getter for Gradient Secondary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicButtonBackgroundGradientSecondaryColor(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicButtonBackgroundGradientSecondaryColor");

		///<summary>
		/// Secondary Color Position (Desktop): Specify the position of the secondary gradient color stop for desktop devices (0-100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicButtonBackgroundGradientSecondaryLocationDesktop")]
		public virtual string BasicButtonBackgroundGradientSecondaryLocationDesktop => GetBasicButtonBackgroundGradientSecondaryLocationDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Secondary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicButtonBackgroundGradientSecondaryLocationDesktop(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicButtonBackgroundGradientSecondaryLocationDesktop");

		///<summary>
		/// Secondary Color Position (Mobile): Specify the position of the secondary gradient color stop for mobile devices (0-100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicButtonBackgroundGradientSecondaryLocationMobile")]
		public virtual string BasicButtonBackgroundGradientSecondaryLocationMobile => GetBasicButtonBackgroundGradientSecondaryLocationMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Secondary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicButtonBackgroundGradientSecondaryLocationMobile(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicButtonBackgroundGradientSecondaryLocationMobile");

		///<summary>
		/// Secondary Color Position (Tablet): Specify the position of the secondary gradient color stop for tablet devices (0-100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicButtonBackgroundGradientSecondaryLocationTablet")]
		public virtual string BasicButtonBackgroundGradientSecondaryLocationTablet => GetBasicButtonBackgroundGradientSecondaryLocationTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Secondary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicButtonBackgroundGradientSecondaryLocationTablet(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicButtonBackgroundGradientSecondaryLocationTablet");

		///<summary>
		/// Gradient Type: Select the gradient type to apply to the background like Linear or Radial
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicButtonBackgroundGradientType")]
		public virtual string BasicButtonBackgroundGradientType => GetBasicButtonBackgroundGradientType(this, _publishedValueFallback);

		/// <summary>Static getter for Gradient Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicButtonBackgroundGradientType(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicButtonBackgroundGradientType");

		///<summary>
		/// Background Type: Select the type of background to apply, such as Classic or Gradient
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicButtonBackgroundType")]
		public virtual string BasicButtonBackgroundType => GetBasicButtonBackgroundType(this, _publishedValueFallback);

		/// <summary>Static getter for Background Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicButtonBackgroundType(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicButtonBackgroundType");

		///<summary>
		/// Background Type - Classic (Label): The following settings apply only when the Background Type is set to Classic.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuignorebasicButtonBackgroundTypeClassic")]
		public virtual string NuignorebasicButtonBackgroundTypeClassic => GetNuignorebasicButtonBackgroundTypeClassic(this, _publishedValueFallback);

		/// <summary>Static getter for Background Type - Classic (Label)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetNuignorebasicButtonBackgroundTypeClassic(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "nuignorebasicButtonBackgroundTypeClassic");

		///<summary>
		/// Background Type - Gradient (Label): The following settings apply only when the Background Type is set to Gradient.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuignorebasicButtonBackgroundTypeGradient")]
		public virtual string NuignorebasicButtonBackgroundTypeGradient => GetNuignorebasicButtonBackgroundTypeGradient(this, _publishedValueFallback);

		/// <summary>Static getter for Background Type - Gradient (Label)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetNuignorebasicButtonBackgroundTypeGradient(IBasicTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "nuignorebasicButtonBackgroundTypeGradient");
	}
}
