//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "basicTagIconThemeSettings"
	/// <summary>[Nubrik][Style][Theme Settings][Basic][Tag] Icon Theme</summary>
	public partial interface IBasicTagIconThemeSettings : IPublishedElement
	{
		/// <summary>Icon Position</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicIconPosition { get; }

		/// <summary>Label Font</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicPfont { get; }

		/// <summary>Label Font Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicPfontColor { get; }

		/// <summary>Label Font Size (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicPfontSizeDesktop { get; }

		/// <summary>Label Font Size (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicPfontSizeMobile { get; }

		/// <summary>Label Font Size (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicPfontSizeTablet { get; }

		/// <summary>Label Letter Spacing (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicPfontSpacingDesktop { get; }

		/// <summary>Label Letter Spacing (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicPfontSpacingMobile { get; }

		/// <summary>Label Letter Spacing (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicPfontSpacingTablet { get; }

		/// <summary>Label Font Style</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicPfontStyle { get; }

		/// <summary>Label Line Height (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicProwHdesktop { get; }

		/// <summary>Label Line Height (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicProwHmobile { get; }

		/// <summary>Label Line Height (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicProwHtablet { get; }

		/// <summary>Tag Icon</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicTagIcon { get; }
	}

	/// <summary>[Nubrik][Style][Theme Settings][Basic][Tag] Icon Theme</summary>
	[PublishedModel("basicTagIconThemeSettings")]
	public partial class BasicTagIconThemeSettings : PublishedElementModel, IBasicTagIconThemeSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "basicTagIconThemeSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<BasicTagIconThemeSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public BasicTagIconThemeSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Icon Position: Specify the position of the icon relative to the tag label, such as Left or Right.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicIconPosition")]
		public virtual string BasicIconPosition => GetBasicIconPosition(this, _publishedValueFallback);

		/// <summary>Static getter for Icon Position</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicIconPosition(IBasicTagIconThemeSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicIconPosition");

		///<summary>
		/// Label Font: Select the font family for the tag label text.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicPFont")]
		public virtual string BasicPfont => GetBasicPfont(this, _publishedValueFallback);

		/// <summary>Static getter for Label Font</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicPfont(IBasicTagIconThemeSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicPFont");

		///<summary>
		/// Label Font Color: Select the color of the tag label text.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicPFontColor")]
		public virtual string BasicPfontColor => GetBasicPfontColor(this, _publishedValueFallback);

		/// <summary>Static getter for Label Font Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicPfontColor(IBasicTagIconThemeSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicPFontColor");

		///<summary>
		/// Label Font Size (Desktop): Specify the font size for the tag label on desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicPFontSizeDesktop")]
		public virtual string BasicPfontSizeDesktop => GetBasicPfontSizeDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Label Font Size (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicPfontSizeDesktop(IBasicTagIconThemeSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicPFontSizeDesktop");

		///<summary>
		/// Label Font Size (Mobile): Specify the font size for the tag label on mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicPFontSizeMobile")]
		public virtual string BasicPfontSizeMobile => GetBasicPfontSizeMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Label Font Size (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicPfontSizeMobile(IBasicTagIconThemeSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicPFontSizeMobile");

		///<summary>
		/// Label Font Size (Tablet): Specify the font size for the tag label on tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicPFontSizeTablet")]
		public virtual string BasicPfontSizeTablet => GetBasicPfontSizeTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Label Font Size (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicPfontSizeTablet(IBasicTagIconThemeSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicPFontSizeTablet");

		///<summary>
		/// Label Letter Spacing (Desktop): Specify the letter spacing for the tag label on desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicPFontSpacingDesktop")]
		public virtual string BasicPfontSpacingDesktop => GetBasicPfontSpacingDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Label Letter Spacing (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicPfontSpacingDesktop(IBasicTagIconThemeSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicPFontSpacingDesktop");

		///<summary>
		/// Label Letter Spacing (Mobile): Specify the letter spacing for the tag label on mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicPFontSpacingMobile")]
		public virtual string BasicPfontSpacingMobile => GetBasicPfontSpacingMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Label Letter Spacing (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicPfontSpacingMobile(IBasicTagIconThemeSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicPFontSpacingMobile");

		///<summary>
		/// Label Letter Spacing (Tablet): Specify the letter spacing for the tag label on tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicPFontSpacingTablet")]
		public virtual string BasicPfontSpacingTablet => GetBasicPfontSpacingTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Label Letter Spacing (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicPfontSpacingTablet(IBasicTagIconThemeSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicPFontSpacingTablet");

		///<summary>
		/// Label Font Style: Select the font style for the tag label, such as Normal, Italic, or Bold.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicPFontStyle")]
		public virtual string BasicPfontStyle => GetBasicPfontStyle(this, _publishedValueFallback);

		/// <summary>Static getter for Label Font Style</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicPfontStyle(IBasicTagIconThemeSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicPFontStyle");

		///<summary>
		/// Label Line Height (Desktop): Specify the line height for the tag label on desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicPRowHDesktop")]
		public virtual string BasicProwHdesktop => GetBasicProwHdesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Label Line Height (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicProwHdesktop(IBasicTagIconThemeSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicPRowHDesktop");

		///<summary>
		/// Label Line Height (Mobile): Specify the line height for the tag label on mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicPRowHMobile")]
		public virtual string BasicProwHmobile => GetBasicProwHmobile(this, _publishedValueFallback);

		/// <summary>Static getter for Label Line Height (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicProwHmobile(IBasicTagIconThemeSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicPRowHMobile");

		///<summary>
		/// Label Line Height (Tablet): Specify the line height for the tag label on tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicPRowHTablet")]
		public virtual string BasicProwHtablet => GetBasicProwHtablet(this, _publishedValueFallback);

		/// <summary>Static getter for Label Line Height (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicProwHtablet(IBasicTagIconThemeSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicPRowHTablet");

		///<summary>
		/// Tag Icon: Select the icon image to display on the tag.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicTagIcon")]
		public virtual string BasicTagIcon => GetBasicTagIcon(this, _publishedValueFallback);

		/// <summary>Static getter for Tag Icon</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicTagIcon(IBasicTagIconThemeSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicTagIcon");
	}
}
