//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "buttonPaddingSettings"
	/// <summary>[Nubrik][Style][Settings][Button] Padding</summary>
	public partial interface IButtonPaddingSettings : IPublishedElement
	{
		/// <summary>Button Padding Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ButtonPaddingBottomDesktop { get; }

		/// <summary>Button Padding Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ButtonPaddingBottomMobile { get; }

		/// <summary>Button Padding Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ButtonPaddingBottomTablet { get; }

		/// <summary>Button Padding Left</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ButtonPaddingLeftDesktop { get; }

		/// <summary>Button Padding Left</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ButtonPaddingLeftMobile { get; }

		/// <summary>Button Padding Left</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ButtonPaddingLeftTablet { get; }

		/// <summary>Button Padding Right</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ButtonPaddingRightDesktop { get; }

		/// <summary>Button Padding Right</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ButtonPaddingRightMobile { get; }

		/// <summary>Button Padding Right</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ButtonPaddingRightTablet { get; }

		/// <summary>Button Padding Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ButtonPaddingTopDesktop { get; }

		/// <summary>Button Padding Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ButtonPaddingTopMobile { get; }

		/// <summary>Button Padding Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ButtonPaddingTopTablet { get; }
	}

	/// <summary>[Nubrik][Style][Settings][Button] Padding</summary>
	[PublishedModel("buttonPaddingSettings")]
	public partial class ButtonPaddingSettings : PublishedElementModel, IButtonPaddingSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "buttonPaddingSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<ButtonPaddingSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ButtonPaddingSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Button Padding Bottom: Button Padding Bottom Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("buttonPaddingBottomDesktop")]
		public virtual string ButtonPaddingBottomDesktop => GetButtonPaddingBottomDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Button Padding Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetButtonPaddingBottomDesktop(IButtonPaddingSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "buttonPaddingBottomDesktop");

		///<summary>
		/// Button Padding Bottom: Button Padding Bottom Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("buttonPaddingBottomMobile")]
		public virtual string ButtonPaddingBottomMobile => GetButtonPaddingBottomMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Button Padding Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetButtonPaddingBottomMobile(IButtonPaddingSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "buttonPaddingBottomMobile");

		///<summary>
		/// Button Padding Bottom: Button Padding Bottom Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("buttonPaddingBottomTablet")]
		public virtual string ButtonPaddingBottomTablet => GetButtonPaddingBottomTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Button Padding Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetButtonPaddingBottomTablet(IButtonPaddingSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "buttonPaddingBottomTablet");

		///<summary>
		/// Button Padding Left: Button Padding Left Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("buttonPaddingLeftDesktop")]
		public virtual string ButtonPaddingLeftDesktop => GetButtonPaddingLeftDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Button Padding Left</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetButtonPaddingLeftDesktop(IButtonPaddingSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "buttonPaddingLeftDesktop");

		///<summary>
		/// Button Padding Left: Button Padding Left Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("buttonPaddingLeftMobile")]
		public virtual string ButtonPaddingLeftMobile => GetButtonPaddingLeftMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Button Padding Left</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetButtonPaddingLeftMobile(IButtonPaddingSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "buttonPaddingLeftMobile");

		///<summary>
		/// Button Padding Left: Button Padding Left Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("buttonPaddingLeftTablet")]
		public virtual string ButtonPaddingLeftTablet => GetButtonPaddingLeftTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Button Padding Left</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetButtonPaddingLeftTablet(IButtonPaddingSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "buttonPaddingLeftTablet");

		///<summary>
		/// Button Padding Right: Button Padding Right Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("buttonPaddingRightDesktop")]
		public virtual string ButtonPaddingRightDesktop => GetButtonPaddingRightDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Button Padding Right</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetButtonPaddingRightDesktop(IButtonPaddingSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "buttonPaddingRightDesktop");

		///<summary>
		/// Button Padding Right: Button Padding Right Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("buttonPaddingRightMobile")]
		public virtual string ButtonPaddingRightMobile => GetButtonPaddingRightMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Button Padding Right</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetButtonPaddingRightMobile(IButtonPaddingSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "buttonPaddingRightMobile");

		///<summary>
		/// Button Padding Right: Button Padding Right Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("buttonPaddingRightTablet")]
		public virtual string ButtonPaddingRightTablet => GetButtonPaddingRightTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Button Padding Right</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetButtonPaddingRightTablet(IButtonPaddingSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "buttonPaddingRightTablet");

		///<summary>
		/// Button Padding Top: Button Padding Top Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("buttonPaddingTopDesktop")]
		public virtual string ButtonPaddingTopDesktop => GetButtonPaddingTopDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Button Padding Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetButtonPaddingTopDesktop(IButtonPaddingSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "buttonPaddingTopDesktop");

		///<summary>
		/// Button Padding Top: Button Padding Top Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("buttonPaddingTopMobile")]
		public virtual string ButtonPaddingTopMobile => GetButtonPaddingTopMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Button Padding Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetButtonPaddingTopMobile(IButtonPaddingSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "buttonPaddingTopMobile");

		///<summary>
		/// Button Padding Top: Button Padding Top Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("buttonPaddingTopTablet")]
		public virtual string ButtonPaddingTopTablet => GetButtonPaddingTopTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Button Padding Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetButtonPaddingTopTablet(IButtonPaddingSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "buttonPaddingTopTablet");
	}
}
