//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "hoverTagsBackgroundTypeSettings1"
	/// <summary>[Nubrik][Style][Theme Settings][Hover][Button] Background Type</summary>
	public partial interface IHoverTagsBackgroundTypeSettings1 : IPublishedElement
	{
		/// <summary>Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverButtonBackgroundColor { get; }

		/// <summary>Gradient Angle (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverButtonBackgroundGradientAngleDesktop { get; }

		/// <summary>Gradient Angle (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverButtonBackgroundGradientAngleMobile { get; }

		/// <summary>Gradient Angle (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverButtonBackgroundGradientAngleTablet { get; }

		/// <summary>Gradient Primary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverButtonBackgroundGradientPrimaryColor { get; }

		/// <summary>Primary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverButtonBackgroundGradientPrimaryLocationDesktop { get; }

		/// <summary>Primary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverButtonBackgroundGradientPrimaryLocationMobile { get; }

		/// <summary>Primary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverButtonBackgroundGradientPrimaryLocationTablet { get; }

		/// <summary>Gradient Secondary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverButtonBackgroundGradientSecondaryColor { get; }

		/// <summary>Secondary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverButtonBackgroundGradientSecondaryLocationDesktop { get; }

		/// <summary>Secondary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverButtonBackgroundGradientSecondaryLocationMobile { get; }

		/// <summary>Secondary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverButtonBackgroundGradientSecondaryLocationTablet { get; }

		/// <summary>Gradient Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverButtonBackgroundGradientType { get; }

		/// <summary>Background Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverButtonBackgroundType { get; }

		/// <summary>Background Type - Classic (Label)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string NuignorehoverButtonBackgroundTypeClassic { get; }

		/// <summary>Background Type - Gradient (Label)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string NuignorehoverButtonBackgroundTypeGradient { get; }
	}

	/// <summary>[Nubrik][Style][Theme Settings][Hover][Button] Background Type</summary>
	[PublishedModel("hoverTagsBackgroundTypeSettings1")]
	public partial class HoverTagsBackgroundTypeSettings1 : PublishedElementModel, IHoverTagsBackgroundTypeSettings1
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "hoverTagsBackgroundTypeSettings1";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<HoverTagsBackgroundTypeSettings1, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public HoverTagsBackgroundTypeSettings1(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Background Color: Select the background color for the button.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverButtonBackgroundColor")]
		public virtual string HoverButtonBackgroundColor => GetHoverButtonBackgroundColor(this, _publishedValueFallback);

		/// <summary>Static getter for Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverButtonBackgroundColor(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverButtonBackgroundColor");

		///<summary>
		/// Gradient Angle (Desktop): Specify the gradient angle for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverButtonBackgroundGradientAngleDesktop")]
		public virtual string HoverButtonBackgroundGradientAngleDesktop => GetHoverButtonBackgroundGradientAngleDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Gradient Angle (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverButtonBackgroundGradientAngleDesktop(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverButtonBackgroundGradientAngleDesktop");

		///<summary>
		/// Gradient Angle (Mobile): Specify the gradient angle for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverButtonBackgroundGradientAngleMobile")]
		public virtual string HoverButtonBackgroundGradientAngleMobile => GetHoverButtonBackgroundGradientAngleMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Gradient Angle (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverButtonBackgroundGradientAngleMobile(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverButtonBackgroundGradientAngleMobile");

		///<summary>
		/// Gradient Angle (Tablet): Specify the gradient angle for tablet devices
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverButtonBackgroundGradientAngleTablet")]
		public virtual string HoverButtonBackgroundGradientAngleTablet => GetHoverButtonBackgroundGradientAngleTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Gradient Angle (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverButtonBackgroundGradientAngleTablet(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverButtonBackgroundGradientAngleTablet");

		///<summary>
		/// Gradient Primary Color: Select the primary color used in the background gradient.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverButtonBackgroundGradientPrimaryColor")]
		public virtual string HoverButtonBackgroundGradientPrimaryColor => GetHoverButtonBackgroundGradientPrimaryColor(this, _publishedValueFallback);

		/// <summary>Static getter for Gradient Primary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverButtonBackgroundGradientPrimaryColor(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverButtonBackgroundGradientPrimaryColor");

		///<summary>
		/// Primary Color Position (Desktop): Specify the position of the primary gradient color stop for desktop devices (0-100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverButtonBackgroundGradientPrimaryLocationDesktop")]
		public virtual string HoverButtonBackgroundGradientPrimaryLocationDesktop => GetHoverButtonBackgroundGradientPrimaryLocationDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Primary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverButtonBackgroundGradientPrimaryLocationDesktop(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverButtonBackgroundGradientPrimaryLocationDesktop");

		///<summary>
		/// Primary Color Position (Mobile): Specify the position of the primary gradient color stop for mobile devices (0-100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverButtonBackgroundGradientPrimaryLocationMobile")]
		public virtual string HoverButtonBackgroundGradientPrimaryLocationMobile => GetHoverButtonBackgroundGradientPrimaryLocationMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Primary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverButtonBackgroundGradientPrimaryLocationMobile(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverButtonBackgroundGradientPrimaryLocationMobile");

		///<summary>
		/// Primary Color Position (Tablet): Specify the position of the primary gradient color stop for tablet devices (0-100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverButtonBackgroundGradientPrimaryLocationTablet")]
		public virtual string HoverButtonBackgroundGradientPrimaryLocationTablet => GetHoverButtonBackgroundGradientPrimaryLocationTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Primary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverButtonBackgroundGradientPrimaryLocationTablet(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverButtonBackgroundGradientPrimaryLocationTablet");

		///<summary>
		/// Gradient Secondary Color: Select the secondary color used in the background gradient.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverButtonBackgroundGradientSecondaryColor")]
		public virtual string HoverButtonBackgroundGradientSecondaryColor => GetHoverButtonBackgroundGradientSecondaryColor(this, _publishedValueFallback);

		/// <summary>Static getter for Gradient Secondary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverButtonBackgroundGradientSecondaryColor(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverButtonBackgroundGradientSecondaryColor");

		///<summary>
		/// Secondary Color Position (Desktop): Specify the position of the secondary gradient color stop for desktop devices (0-100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverButtonBackgroundGradientSecondaryLocationDesktop")]
		public virtual string HoverButtonBackgroundGradientSecondaryLocationDesktop => GetHoverButtonBackgroundGradientSecondaryLocationDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Secondary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverButtonBackgroundGradientSecondaryLocationDesktop(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverButtonBackgroundGradientSecondaryLocationDesktop");

		///<summary>
		/// Secondary Color Position (Mobile): Specify the position of the secondary gradient color stop for mobile devices (0-100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverButtonBackgroundGradientSecondaryLocationMobile")]
		public virtual string HoverButtonBackgroundGradientSecondaryLocationMobile => GetHoverButtonBackgroundGradientSecondaryLocationMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Secondary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverButtonBackgroundGradientSecondaryLocationMobile(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverButtonBackgroundGradientSecondaryLocationMobile");

		///<summary>
		/// Secondary Color Position (Tablet): Specify the position of the secondary gradient color stop for tablet devices (0-100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverButtonBackgroundGradientSecondaryLocationTablet")]
		public virtual string HoverButtonBackgroundGradientSecondaryLocationTablet => GetHoverButtonBackgroundGradientSecondaryLocationTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Secondary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverButtonBackgroundGradientSecondaryLocationTablet(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverButtonBackgroundGradientSecondaryLocationTablet");

		///<summary>
		/// Gradient Type: Select the gradient type to apply to the background like Linear or Radial
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverButtonBackgroundGradientType")]
		public virtual string HoverButtonBackgroundGradientType => GetHoverButtonBackgroundGradientType(this, _publishedValueFallback);

		/// <summary>Static getter for Gradient Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverButtonBackgroundGradientType(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverButtonBackgroundGradientType");

		///<summary>
		/// Background Type: Select the type of background to apply, such as Classic or Gradient
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverButtonBackgroundType")]
		public virtual string HoverButtonBackgroundType => GetHoverButtonBackgroundType(this, _publishedValueFallback);

		/// <summary>Static getter for Background Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverButtonBackgroundType(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverButtonBackgroundType");

		///<summary>
		/// Background Type - Classic (Label): The following settings apply only when the Background Type is set to Classic.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuignorehoverButtonBackgroundTypeClassic")]
		public virtual string NuignorehoverButtonBackgroundTypeClassic => GetNuignorehoverButtonBackgroundTypeClassic(this, _publishedValueFallback);

		/// <summary>Static getter for Background Type - Classic (Label)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetNuignorehoverButtonBackgroundTypeClassic(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "nuignorehoverButtonBackgroundTypeClassic");

		///<summary>
		/// Background Type - Gradient (Label): The following settings apply only when the Background Type is set to Gradient.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuignorehoverButtonBackgroundTypeGradient")]
		public virtual string NuignorehoverButtonBackgroundTypeGradient => GetNuignorehoverButtonBackgroundTypeGradient(this, _publishedValueFallback);

		/// <summary>Static getter for Background Type - Gradient (Label)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetNuignorehoverButtonBackgroundTypeGradient(IHoverTagsBackgroundTypeSettings1 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "nuignorehoverButtonBackgroundTypeGradient");
	}
}
