//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "hoverBackgroundTypeGradientSettings"
	/// <summary>[Nubrik]{Style][Settings]{Layout][Hover] Background Type Gradient</summary>
	public partial interface IHoverBackgroundTypeGradientSettings : IPublishedElement
	{
		/// <summary>Angle Desktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBackgroundGradientAngleDesktop { get; }

		/// <summary>Angle Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBackgroundGradientAngleMobile { get; }

		/// <summary>Angle Tablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBackgroundGradientAngleTablet { get; }

		/// <summary>Primary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBackgroundGradientPrimaryColor { get; }

		/// <summary>Location Desktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBackgroundGradientPrimaryLocationDesktop { get; }

		/// <summary>Location Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBackgroundGradientPrimaryLocationMobile { get; }

		/// <summary>Location Tablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBackgroundGradientPrimaryLocationTablet { get; }

		/// <summary>Secondary color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBackgroundGradientSecondaryColor { get; }

		/// <summary>Location</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBackgroundGradientSecondaryLocationDesktop { get; }

		/// <summary>Location</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBackgroundGradientSecondaryLocationMobile { get; }

		/// <summary>Location</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBackgroundGradientSecondaryLocationTablet { get; }

		/// <summary>Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBackgroundGradientType { get; }

		/// <summary>BackgroundType-Gradient</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string NuignoreHoverBackgroundTypeGradient { get; }
	}

	/// <summary>[Nubrik]{Style][Settings]{Layout][Hover] Background Type Gradient</summary>
	[PublishedModel("hoverBackgroundTypeGradientSettings")]
	public partial class HoverBackgroundTypeGradientSettings : PublishedElementModel, IHoverBackgroundTypeGradientSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "hoverBackgroundTypeGradientSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<HoverBackgroundTypeGradientSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public HoverBackgroundTypeGradientSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Angle Desktop: Gradient Angle Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientAngleDesktop")]
		public virtual string HoverBackgroundGradientAngleDesktop => GetHoverBackgroundGradientAngleDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Angle Desktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBackgroundGradientAngleDesktop(IHoverBackgroundTypeGradientSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBackgroundGradientAngleDesktop");

		///<summary>
		/// Angle Mobile: Gradient Angle Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientAngleMobile")]
		public virtual string HoverBackgroundGradientAngleMobile => GetHoverBackgroundGradientAngleMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Angle Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBackgroundGradientAngleMobile(IHoverBackgroundTypeGradientSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBackgroundGradientAngleMobile");

		///<summary>
		/// Angle Tablet: Gradient Angle Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientAngleTablet")]
		public virtual string HoverBackgroundGradientAngleTablet => GetHoverBackgroundGradientAngleTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Angle Tablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBackgroundGradientAngleTablet(IHoverBackgroundTypeGradientSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBackgroundGradientAngleTablet");

		///<summary>
		/// Primary Color: Background Gradient Primary Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientPrimaryColor")]
		public virtual string HoverBackgroundGradientPrimaryColor => GetHoverBackgroundGradientPrimaryColor(this, _publishedValueFallback);

		/// <summary>Static getter for Primary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBackgroundGradientPrimaryColor(IHoverBackgroundTypeGradientSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBackgroundGradientPrimaryColor");

		///<summary>
		/// Location Desktop: Background Gradient Primary Location Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientPrimaryLocationDesktop")]
		public virtual string HoverBackgroundGradientPrimaryLocationDesktop => GetHoverBackgroundGradientPrimaryLocationDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Location Desktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBackgroundGradientPrimaryLocationDesktop(IHoverBackgroundTypeGradientSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBackgroundGradientPrimaryLocationDesktop");

		///<summary>
		/// Location Mobile: Background Gradient Primary Location Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientPrimaryLocationMobile")]
		public virtual string HoverBackgroundGradientPrimaryLocationMobile => GetHoverBackgroundGradientPrimaryLocationMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Location Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBackgroundGradientPrimaryLocationMobile(IHoverBackgroundTypeGradientSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBackgroundGradientPrimaryLocationMobile");

		///<summary>
		/// Location Tablet: Background Gradient Primary Location Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientPrimaryLocationTablet")]
		public virtual string HoverBackgroundGradientPrimaryLocationTablet => GetHoverBackgroundGradientPrimaryLocationTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Location Tablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBackgroundGradientPrimaryLocationTablet(IHoverBackgroundTypeGradientSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBackgroundGradientPrimaryLocationTablet");

		///<summary>
		/// Secondary color: Background Gradient Secondary Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientSecondaryColor")]
		public virtual string HoverBackgroundGradientSecondaryColor => GetHoverBackgroundGradientSecondaryColor(this, _publishedValueFallback);

		/// <summary>Static getter for Secondary color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBackgroundGradientSecondaryColor(IHoverBackgroundTypeGradientSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBackgroundGradientSecondaryColor");

		///<summary>
		/// Location: Background Gradient Secondary Location Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientSecondaryLocationDesktop")]
		public virtual string HoverBackgroundGradientSecondaryLocationDesktop => GetHoverBackgroundGradientSecondaryLocationDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Location</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBackgroundGradientSecondaryLocationDesktop(IHoverBackgroundTypeGradientSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBackgroundGradientSecondaryLocationDesktop");

		///<summary>
		/// Location: Background Gradient Secondary Location Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientSecondaryLocationMobile")]
		public virtual string HoverBackgroundGradientSecondaryLocationMobile => GetHoverBackgroundGradientSecondaryLocationMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Location</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBackgroundGradientSecondaryLocationMobile(IHoverBackgroundTypeGradientSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBackgroundGradientSecondaryLocationMobile");

		///<summary>
		/// Location: Background Gradient Secondary Location Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientSecondaryLocationTablet")]
		public virtual string HoverBackgroundGradientSecondaryLocationTablet => GetHoverBackgroundGradientSecondaryLocationTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Location</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBackgroundGradientSecondaryLocationTablet(IHoverBackgroundTypeGradientSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBackgroundGradientSecondaryLocationTablet");

		///<summary>
		/// Type: Gradient Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientType")]
		public virtual string HoverBackgroundGradientType => GetHoverBackgroundGradientType(this, _publishedValueFallback);

		/// <summary>Static getter for Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBackgroundGradientType(IHoverBackgroundTypeGradientSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBackgroundGradientType");

		///<summary>
		/// BackgroundType-Gradient
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuignoreHoverBackgroundTypeGradient")]
		public virtual string NuignoreHoverBackgroundTypeGradient => GetNuignoreHoverBackgroundTypeGradient(this, _publishedValueFallback);

		/// <summary>Static getter for BackgroundType-Gradient</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetNuignoreHoverBackgroundTypeGradient(IHoverBackgroundTypeGradientSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "nuignoreHoverBackgroundTypeGradient");
	}
}
