//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "hoverBoxesBackgroundOverlaySettings"
	/// <summary>[Nubrik][Style][Settings][Hover][Boxes] Background Overlay</summary>
	public partial interface IHoverBoxesBackgroundOverlaySettings : IPublishedElement
	{
		/// <summary>Overlay Angle (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlayAngleDesktop { get; }

		/// <summary>Overlay Angle (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlayAngleMobile { get; }

		/// <summary>Overlay Angle (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlayAngleTablet { get; }

		/// <summary>Overlay Opacity (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlayOpacityDesktop { get; }

		/// <summary>Overlay Opacity (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlayOpacityMobile { get; }

		/// <summary>Overlay Opacity (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlayOpacityTablet { get; }

		/// <summary>Overlay Primary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlayPrimaryColor { get; }

		/// <summary>Primary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlayPrimaryLocationDesktop { get; }

		/// <summary>Primary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlayPrimaryLocationMobile { get; }

		/// <summary>Primary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlayPrimaryLocationTablet { get; }

		/// <summary>Overlay Secondary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlaySecondaryColor { get; }

		/// <summary>Secondary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlaySecondaryLocationDesktop { get; }

		/// <summary>Secondary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlaySecondaryLocationMobile { get; }

		/// <summary>Secondary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlaySecondaryLocationTablet { get; }

		/// <summary>Overlay Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverBoxesBackgroundOverlayType { get; }

		/// <summary>Background OverlayType - Gradient</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string NuignorehoverBoxesBackgroundOverlayTypeGradient { get; }

		/// <summary>Background OverlayType - Solid</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string NuignorehoverBoxesBackgroundOverlayTypeSolid { get; }
	}

	/// <summary>[Nubrik][Style][Settings][Hover][Boxes] Background Overlay</summary>
	[PublishedModel("hoverBoxesBackgroundOverlaySettings")]
	public partial class HoverBoxesBackgroundOverlaySettings : PublishedElementModel, IHoverBoxesBackgroundOverlaySettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "hoverBoxesBackgroundOverlaySettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<HoverBoxesBackgroundOverlaySettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public HoverBoxesBackgroundOverlaySettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Overlay Angle (Desktop): Specify the angle of the background overlay gradient for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlayAngleDesktop")]
		public virtual string HoverBoxesBackgroundOverlayAngleDesktop => GetHoverBoxesBackgroundOverlayAngleDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Angle (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlayAngleDesktop(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlayAngleDesktop");

		///<summary>
		/// Overlay Angle (Mobile): Specify the angle of the background overlay gradient for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlayAngleMobile")]
		public virtual string HoverBoxesBackgroundOverlayAngleMobile => GetHoverBoxesBackgroundOverlayAngleMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Angle (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlayAngleMobile(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlayAngleMobile");

		///<summary>
		/// Overlay Angle (Tablet): Specify the angle of the background overlay gradient for tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlayAngleTablet")]
		public virtual string HoverBoxesBackgroundOverlayAngleTablet => GetHoverBoxesBackgroundOverlayAngleTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Angle (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlayAngleTablet(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlayAngleTablet");

		///<summary>
		/// Overlay Opacity (Desktop): Set the transparency level of the background overlay for desktop devices (0–100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlayOpacityDesktop")]
		public virtual string HoverBoxesBackgroundOverlayOpacityDesktop => GetHoverBoxesBackgroundOverlayOpacityDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Opacity (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlayOpacityDesktop(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlayOpacityDesktop");

		///<summary>
		/// Overlay Opacity (Mobile): Set the transparency level of the background overlay for mobile devices (0–100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlayOpacityMobile")]
		public virtual string HoverBoxesBackgroundOverlayOpacityMobile => GetHoverBoxesBackgroundOverlayOpacityMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Opacity (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlayOpacityMobile(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlayOpacityMobile");

		///<summary>
		/// Overlay Opacity (Tablet): Set the transparency level of the background overlay for tablet devices (0–100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlayOpacityTablet")]
		public virtual string HoverBoxesBackgroundOverlayOpacityTablet => GetHoverBoxesBackgroundOverlayOpacityTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Opacity (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlayOpacityTablet(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlayOpacityTablet");

		///<summary>
		/// Overlay Primary Color: Select the primary color used in the background overlay.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlayPrimaryColor")]
		public virtual string HoverBoxesBackgroundOverlayPrimaryColor => GetHoverBoxesBackgroundOverlayPrimaryColor(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Primary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlayPrimaryColor(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlayPrimaryColor");

		///<summary>
		/// Primary Color Position (Desktop): Specify the position of the primary overlay color stop for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlayPrimaryLocationDesktop")]
		public virtual string HoverBoxesBackgroundOverlayPrimaryLocationDesktop => GetHoverBoxesBackgroundOverlayPrimaryLocationDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Primary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlayPrimaryLocationDesktop(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlayPrimaryLocationDesktop");

		///<summary>
		/// Primary Color Position (Mobile): Specify the position of the primary overlay color stop for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlayPrimaryLocationMobile")]
		public virtual string HoverBoxesBackgroundOverlayPrimaryLocationMobile => GetHoverBoxesBackgroundOverlayPrimaryLocationMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Primary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlayPrimaryLocationMobile(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlayPrimaryLocationMobile");

		///<summary>
		/// Primary Color Position (Tablet): Specify the position of the primary overlay color stop for tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlayPrimaryLocationTablet")]
		public virtual string HoverBoxesBackgroundOverlayPrimaryLocationTablet => GetHoverBoxesBackgroundOverlayPrimaryLocationTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Primary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlayPrimaryLocationTablet(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlayPrimaryLocationTablet");

		///<summary>
		/// Overlay Secondary Color: Select the secondary color used in the background overlay gradient.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlaySecondaryColor")]
		public virtual string HoverBoxesBackgroundOverlaySecondaryColor => GetHoverBoxesBackgroundOverlaySecondaryColor(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Secondary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlaySecondaryColor(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlaySecondaryColor");

		///<summary>
		/// Secondary Color Position (Desktop): Specify the position of the secondary overlay color stop for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlaySecondaryLocationDesktop")]
		public virtual string HoverBoxesBackgroundOverlaySecondaryLocationDesktop => GetHoverBoxesBackgroundOverlaySecondaryLocationDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Secondary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlaySecondaryLocationDesktop(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlaySecondaryLocationDesktop");

		///<summary>
		/// Secondary Color Position (Mobile): Specify the position of the secondary overlay color stop for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlaySecondaryLocationMobile")]
		public virtual string HoverBoxesBackgroundOverlaySecondaryLocationMobile => GetHoverBoxesBackgroundOverlaySecondaryLocationMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Secondary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlaySecondaryLocationMobile(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlaySecondaryLocationMobile");

		///<summary>
		/// Secondary Color Position (Tablet): Specify the position of the secondary overlay color stop for tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlaySecondaryLocationTablet")]
		public virtual string HoverBoxesBackgroundOverlaySecondaryLocationTablet => GetHoverBoxesBackgroundOverlaySecondaryLocationTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Secondary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlaySecondaryLocationTablet(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlaySecondaryLocationTablet");

		///<summary>
		/// Overlay Type: Select the type of background overlay to apply (for example, Solid or Gradient).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBoxesBackgroundOverlayType")]
		public virtual string HoverBoxesBackgroundOverlayType => GetHoverBoxesBackgroundOverlayType(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverBoxesBackgroundOverlayType(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverBoxesBackgroundOverlayType");

		///<summary>
		/// Background OverlayType - Gradient: The following settings apply only when the Background Overlay Type is set to Gradient.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuignorehoverBoxesBackgroundOverlayTypeGradient")]
		public virtual string NuignorehoverBoxesBackgroundOverlayTypeGradient => GetNuignorehoverBoxesBackgroundOverlayTypeGradient(this, _publishedValueFallback);

		/// <summary>Static getter for Background OverlayType - Gradient</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetNuignorehoverBoxesBackgroundOverlayTypeGradient(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "nuignorehoverBoxesBackgroundOverlayTypeGradient");

		///<summary>
		/// Background OverlayType - Solid: The following settings apply only when the Background Overlay Type is set to Solid.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuignorehoverBoxesBackgroundOverlayTypeSolid")]
		public virtual string NuignorehoverBoxesBackgroundOverlayTypeSolid => GetNuignorehoverBoxesBackgroundOverlayTypeSolid(this, _publishedValueFallback);

		/// <summary>Static getter for Background OverlayType - Solid</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetNuignorehoverBoxesBackgroundOverlayTypeSolid(IHoverBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "nuignorehoverBoxesBackgroundOverlayTypeSolid");
	}
}
