//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "hoverIconsBoxshadowSettings"
	/// <summary>[Nubrik][Style][Theme Settings][Hover] [Icon] Boxshadow</summary>
	public partial interface IHoverIconsBoxshadowSettings : IPublishedElement
	{
		/// <summary>Shadow Blur Radius</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverIconsBorderBlur { get; }

		/// <summary>Shadow Horizontal Offset</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverIconsBorderHorizontal { get; }

		/// <summary>Shadow Position</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverIconsBorderPosition { get; }

		/// <summary>Shadow Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverIconsBorderShadowColor { get; }

		/// <summary>Shadow Spread Radius</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverIconsBorderSpread { get; }

		/// <summary>Shadow Vertical Offset</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverIconsBorderVertical { get; }
	}

	/// <summary>[Nubrik][Style][Theme Settings][Hover] [Icon] Boxshadow</summary>
	[PublishedModel("hoverIconsBoxshadowSettings")]
	public partial class HoverIconsBoxshadowSettings : PublishedElementModel, IHoverIconsBoxshadowSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "hoverIconsBoxshadowSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<HoverIconsBoxshadowSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public HoverIconsBoxshadowSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Shadow Blur Radius: Specify the blur radius of the icon shadow. Higher values create a softer shadow effect.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverIconsBorderBlur")]
		public virtual string HoverIconsBorderBlur => GetHoverIconsBorderBlur(this, _publishedValueFallback);

		/// <summary>Static getter for Shadow Blur Radius</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverIconsBorderBlur(IHoverIconsBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverIconsBorderBlur");

		///<summary>
		/// Shadow Horizontal Offset: Specify the horizontal offset of the icon shadow. Positive values move the shadow to the right, and negative values move it to the left.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverIconsBorderHorizontal")]
		public virtual string HoverIconsBorderHorizontal => GetHoverIconsBorderHorizontal(this, _publishedValueFallback);

		/// <summary>Static getter for Shadow Horizontal Offset</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverIconsBorderHorizontal(IHoverIconsBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverIconsBorderHorizontal");

		///<summary>
		/// Shadow Position: Select whether the icon shadow appears inside (Inset) or outside (Outline) the icon.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverIconsBorderPosition")]
		public virtual string HoverIconsBorderPosition => GetHoverIconsBorderPosition(this, _publishedValueFallback);

		/// <summary>Static getter for Shadow Position</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverIconsBorderPosition(IHoverIconsBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverIconsBorderPosition");

		///<summary>
		/// Shadow Color: Select the color of the icon shadow.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverIconsBorderShadowColor")]
		public virtual string HoverIconsBorderShadowColor => GetHoverIconsBorderShadowColor(this, _publishedValueFallback);

		/// <summary>Static getter for Shadow Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverIconsBorderShadowColor(IHoverIconsBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverIconsBorderShadowColor");

		///<summary>
		/// Shadow Spread Radius: Specify the spread radius of the icon shadow. Positive values increase the shadow size, while negative values decrease it.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverIconsBorderSpread")]
		public virtual string HoverIconsBorderSpread => GetHoverIconsBorderSpread(this, _publishedValueFallback);

		/// <summary>Static getter for Shadow Spread Radius</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverIconsBorderSpread(IHoverIconsBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverIconsBorderSpread");

		///<summary>
		/// Shadow Vertical Offset: Specify the vertical offset of the icon shadow. Positive values move the shadow downward, and negative values move it upward.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverIconsBorderVertical")]
		public virtual string HoverIconsBorderVertical => GetHoverIconsBorderVertical(this, _publishedValueFallback);

		/// <summary>Static getter for Shadow Vertical Offset</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverIconsBorderVertical(IHoverIconsBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverIconsBorderVertical");
	}
}
