//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "hoverTagsBoxshadowSettings"
	/// <summary>[Nubrik][Style][Theme Settings][Hover][Tags] Boxshadow</summary>
	public partial interface IHoverTagsBoxshadowSettings : IPublishedElement
	{
		/// <summary>Shadow Blur Radius</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverTagsBorderBlur { get; }

		/// <summary>Shadow Horizontal Offset</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverTagsBorderHorizontal { get; }

		/// <summary>Shadow Position</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverTagsBorderPosition { get; }

		/// <summary>Shadow Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverTagsBorderShadowColor { get; }

		/// <summary>Shadow Spread Radius</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverTagsBorderSpread { get; }

		/// <summary>Shadow Vertical Offset</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HoverTagsBorderVertical { get; }
	}

	/// <summary>[Nubrik][Style][Theme Settings][Hover][Tags] Boxshadow</summary>
	[PublishedModel("hoverTagsBoxshadowSettings")]
	public partial class HoverTagsBoxshadowSettings : PublishedElementModel, IHoverTagsBoxshadowSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "hoverTagsBoxshadowSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<HoverTagsBoxshadowSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public HoverTagsBoxshadowSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Shadow Blur Radius: Specify the blur radius of the tag shadow. Higher values create a softer shadow effect.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverTagsBorderBlur")]
		public virtual string HoverTagsBorderBlur => GetHoverTagsBorderBlur(this, _publishedValueFallback);

		/// <summary>Static getter for Shadow Blur Radius</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverTagsBorderBlur(IHoverTagsBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverTagsBorderBlur");

		///<summary>
		/// Shadow Horizontal Offset: Specify the horizontal offset of the tag shadow. Positive values move the shadow to the right, and negative values move it to the left.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverTagsBorderHorizontal")]
		public virtual string HoverTagsBorderHorizontal => GetHoverTagsBorderHorizontal(this, _publishedValueFallback);

		/// <summary>Static getter for Shadow Horizontal Offset</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverTagsBorderHorizontal(IHoverTagsBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverTagsBorderHorizontal");

		///<summary>
		/// Shadow Position: Select whether the tag shadow appears inside (Inset) or outside (Outline) the tag.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverTagsBorderPosition")]
		public virtual string HoverTagsBorderPosition => GetHoverTagsBorderPosition(this, _publishedValueFallback);

		/// <summary>Static getter for Shadow Position</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverTagsBorderPosition(IHoverTagsBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverTagsBorderPosition");

		///<summary>
		/// Shadow Color: Select the color of the tag shadow.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverTagsBorderShadowColor")]
		public virtual string HoverTagsBorderShadowColor => GetHoverTagsBorderShadowColor(this, _publishedValueFallback);

		/// <summary>Static getter for Shadow Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverTagsBorderShadowColor(IHoverTagsBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverTagsBorderShadowColor");

		///<summary>
		/// Shadow Spread Radius: Specify the spread radius of the tag shadow. Positive values increase the shadow size, while negative values decrease it.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverTagsBorderSpread")]
		public virtual string HoverTagsBorderSpread => GetHoverTagsBorderSpread(this, _publishedValueFallback);

		/// <summary>Static getter for Shadow Spread Radius</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverTagsBorderSpread(IHoverTagsBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverTagsBorderSpread");

		///<summary>
		/// Shadow Vertical Offset: Specify the vertical offset of the tag shadow. Positive values move the shadow downward, and negative values move it upward.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverTagsBorderVertical")]
		public virtual string HoverTagsBorderVertical => GetHoverTagsBorderVertical(this, _publishedValueFallback);

		/// <summary>Static getter for Shadow Vertical Offset</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHoverTagsBorderVertical(IHoverTagsBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "hoverTagsBorderVertical");
	}
}
