//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "layoutContainerSettings"
	/// <summary>[Nubrik][Style][Settings][Layout Container]</summary>
	public partial interface ILayoutContainerSettings : IPublishedElement
	{
		/// <summary>containerColumnCount</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContainerColumnCount { get; }

		/// <summary>containerItemsColumnGapDesktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContainerItemsColumnGapDesktop { get; }

		/// <summary>containerItemsColumnGapMobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContainerItemsColumnGapMobile { get; }

		/// <summary>containerItemsColumnGapTablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContainerItemsColumnGapTablet { get; }

		/// <summary>containerItemsFlexDirectionDesktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContainerItemsFlexDirectionDesktop { get; }

		/// <summary>containerItemsFlexDirectionMobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContainerItemsFlexDirectionMobile { get; }

		/// <summary>containerItemsFlexDirectionTablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContainerItemsFlexDirectionTablet { get; }

		/// <summary>containerItemsRowGapDesktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContainerItemsRowGapDesktop { get; }

		/// <summary>containerItemsRowGapMobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContainerItemsRowGapMobile { get; }

		/// <summary>containerItemsRowGapTablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContainerItemsRowGapTablet { get; }

		/// <summary>containerItemsWrapDesktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContainerItemsWrapDesktop { get; }

		/// <summary>containerItemsWrapMobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContainerItemsWrapMobile { get; }

		/// <summary>containerItemsWrapTablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string ContainerItemsWrapTablet { get; }

		/// <summary>flexDirectionDesktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string FlexDirectionDesktop { get; }

		/// <summary>flexDirectionMobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string FlexDirectionMobile { get; }

		/// <summary>flexDirectionTablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string FlexDirectionTablet { get; }

		/// <summary>horizontalAlignmentDesktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HorizontalAlignmentDesktop { get; }

		/// <summary>horizontalAlignmentMobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HorizontalAlignmentMobile { get; }

		/// <summary>horizontalAlignmentTablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string HorizontalAlignmentTablet { get; }

		/// <summary>Container Max Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string SpacingContainerMaxWidthDesktop { get; }

		/// <summary>Container Max Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string SpacingContainerMaxWidthMobile { get; }

		/// <summary>Container Max Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string SpacingContainerMaxWidthTablet { get; }

		/// <summary>verticalAlignmentDesktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string VerticalAlignmentDesktop { get; }

		/// <summary>verticalAlignmentMobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string VerticalAlignmentMobile { get; }

		/// <summary>verticalAlignmentTablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string VerticalAlignmentTablet { get; }
	}

	/// <summary>[Nubrik][Style][Settings][Layout Container]</summary>
	[PublishedModel("layoutContainerSettings")]
	public partial class LayoutContainerSettings : PublishedElementModel, ILayoutContainerSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "layoutContainerSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<LayoutContainerSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public LayoutContainerSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// containerColumnCount
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerColumnCount")]
		public virtual string ContainerColumnCount => GetContainerColumnCount(this, _publishedValueFallback);

		/// <summary>Static getter for containerColumnCount</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContainerColumnCount(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "containerColumnCount");

		///<summary>
		/// containerItemsColumnGapDesktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerItemsColumnGapDesktop")]
		public virtual string ContainerItemsColumnGapDesktop => GetContainerItemsColumnGapDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for containerItemsColumnGapDesktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContainerItemsColumnGapDesktop(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "containerItemsColumnGapDesktop");

		///<summary>
		/// containerItemsColumnGapMobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerItemsColumnGapMobile")]
		public virtual string ContainerItemsColumnGapMobile => GetContainerItemsColumnGapMobile(this, _publishedValueFallback);

		/// <summary>Static getter for containerItemsColumnGapMobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContainerItemsColumnGapMobile(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "containerItemsColumnGapMobile");

		///<summary>
		/// containerItemsColumnGapTablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerItemsColumnGapTablet")]
		public virtual string ContainerItemsColumnGapTablet => GetContainerItemsColumnGapTablet(this, _publishedValueFallback);

		/// <summary>Static getter for containerItemsColumnGapTablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContainerItemsColumnGapTablet(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "containerItemsColumnGapTablet");

		///<summary>
		/// containerItemsFlexDirectionDesktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerItemsFlexDirectionDesktop")]
		public virtual string ContainerItemsFlexDirectionDesktop => GetContainerItemsFlexDirectionDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for containerItemsFlexDirectionDesktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContainerItemsFlexDirectionDesktop(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "containerItemsFlexDirectionDesktop");

		///<summary>
		/// containerItemsFlexDirectionMobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerItemsFlexDirectionMobile")]
		public virtual string ContainerItemsFlexDirectionMobile => GetContainerItemsFlexDirectionMobile(this, _publishedValueFallback);

		/// <summary>Static getter for containerItemsFlexDirectionMobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContainerItemsFlexDirectionMobile(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "containerItemsFlexDirectionMobile");

		///<summary>
		/// containerItemsFlexDirectionTablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerItemsFlexDirectionTablet")]
		public virtual string ContainerItemsFlexDirectionTablet => GetContainerItemsFlexDirectionTablet(this, _publishedValueFallback);

		/// <summary>Static getter for containerItemsFlexDirectionTablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContainerItemsFlexDirectionTablet(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "containerItemsFlexDirectionTablet");

		///<summary>
		/// containerItemsRowGapDesktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerItemsRowGapDesktop")]
		public virtual string ContainerItemsRowGapDesktop => GetContainerItemsRowGapDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for containerItemsRowGapDesktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContainerItemsRowGapDesktop(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "containerItemsRowGapDesktop");

		///<summary>
		/// containerItemsRowGapMobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerItemsRowGapMobile")]
		public virtual string ContainerItemsRowGapMobile => GetContainerItemsRowGapMobile(this, _publishedValueFallback);

		/// <summary>Static getter for containerItemsRowGapMobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContainerItemsRowGapMobile(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "containerItemsRowGapMobile");

		///<summary>
		/// containerItemsRowGapTablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerItemsRowGapTablet")]
		public virtual string ContainerItemsRowGapTablet => GetContainerItemsRowGapTablet(this, _publishedValueFallback);

		/// <summary>Static getter for containerItemsRowGapTablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContainerItemsRowGapTablet(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "containerItemsRowGapTablet");

		///<summary>
		/// containerItemsWrapDesktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerItemsWrapDesktop")]
		public virtual string ContainerItemsWrapDesktop => GetContainerItemsWrapDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for containerItemsWrapDesktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContainerItemsWrapDesktop(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "containerItemsWrapDesktop");

		///<summary>
		/// containerItemsWrapMobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerItemsWrapMobile")]
		public virtual string ContainerItemsWrapMobile => GetContainerItemsWrapMobile(this, _publishedValueFallback);

		/// <summary>Static getter for containerItemsWrapMobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContainerItemsWrapMobile(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "containerItemsWrapMobile");

		///<summary>
		/// containerItemsWrapTablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerItemsWrapTablet")]
		public virtual string ContainerItemsWrapTablet => GetContainerItemsWrapTablet(this, _publishedValueFallback);

		/// <summary>Static getter for containerItemsWrapTablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetContainerItemsWrapTablet(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "containerItemsWrapTablet");

		///<summary>
		/// flexDirectionDesktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("flexDirectionDesktop")]
		public virtual string FlexDirectionDesktop => GetFlexDirectionDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for flexDirectionDesktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetFlexDirectionDesktop(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "flexDirectionDesktop");

		///<summary>
		/// flexDirectionMobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("flexDirectionMobile")]
		public virtual string FlexDirectionMobile => GetFlexDirectionMobile(this, _publishedValueFallback);

		/// <summary>Static getter for flexDirectionMobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetFlexDirectionMobile(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "flexDirectionMobile");

		///<summary>
		/// flexDirectionTablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("flexDirectionTablet")]
		public virtual string FlexDirectionTablet => GetFlexDirectionTablet(this, _publishedValueFallback);

		/// <summary>Static getter for flexDirectionTablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetFlexDirectionTablet(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "flexDirectionTablet");

		///<summary>
		/// horizontalAlignmentDesktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("horizontalAlignmentDesktop")]
		public virtual string HorizontalAlignmentDesktop => GetHorizontalAlignmentDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for horizontalAlignmentDesktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHorizontalAlignmentDesktop(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "horizontalAlignmentDesktop");

		///<summary>
		/// horizontalAlignmentMobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("horizontalAlignmentMobile")]
		public virtual string HorizontalAlignmentMobile => GetHorizontalAlignmentMobile(this, _publishedValueFallback);

		/// <summary>Static getter for horizontalAlignmentMobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHorizontalAlignmentMobile(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "horizontalAlignmentMobile");

		///<summary>
		/// horizontalAlignmentTablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("horizontalAlignmentTablet")]
		public virtual string HorizontalAlignmentTablet => GetHorizontalAlignmentTablet(this, _publishedValueFallback);

		/// <summary>Static getter for horizontalAlignmentTablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetHorizontalAlignmentTablet(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "horizontalAlignmentTablet");

		///<summary>
		/// Container Max Width: Spacing Container Maxwidth Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingContainerMaxWidthDesktop")]
		public virtual string SpacingContainerMaxWidthDesktop => GetSpacingContainerMaxWidthDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Container Max Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetSpacingContainerMaxWidthDesktop(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "spacingContainerMaxWidthDesktop");

		///<summary>
		/// Container Max Width: Spacing Container Maxwidth Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingContainerMaxWidthMobile")]
		public virtual string SpacingContainerMaxWidthMobile => GetSpacingContainerMaxWidthMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Container Max Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetSpacingContainerMaxWidthMobile(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "spacingContainerMaxWidthMobile");

		///<summary>
		/// Container Max Width: Spacing Container Maxwidth Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingContainerMaxWidthTablet")]
		public virtual string SpacingContainerMaxWidthTablet => GetSpacingContainerMaxWidthTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Container Max Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetSpacingContainerMaxWidthTablet(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "spacingContainerMaxWidthTablet");

		///<summary>
		/// verticalAlignmentDesktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("verticalAlignmentDesktop")]
		public virtual string VerticalAlignmentDesktop => GetVerticalAlignmentDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for verticalAlignmentDesktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetVerticalAlignmentDesktop(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "verticalAlignmentDesktop");

		///<summary>
		/// verticalAlignmentMobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("verticalAlignmentMobile")]
		public virtual string VerticalAlignmentMobile => GetVerticalAlignmentMobile(this, _publishedValueFallback);

		/// <summary>Static getter for verticalAlignmentMobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetVerticalAlignmentMobile(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "verticalAlignmentMobile");

		///<summary>
		/// verticalAlignmentTablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("verticalAlignmentTablet")]
		public virtual string VerticalAlignmentTablet => GetVerticalAlignmentTablet(this, _publishedValueFallback);

		/// <summary>Static getter for verticalAlignmentTablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetVerticalAlignmentTablet(ILayoutContainerSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "verticalAlignmentTablet");
	}
}
