//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "marginSettings3"
	/// <summary>[Nubrik][Style][Theme Settings][Basic][Tags] Margin</summary>
	public partial interface IMarginSettings3 : IPublishedElement
	{
		/// <summary>Margin Bottom (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicTagsspacingMarginBottomDesktop { get; }

		/// <summary>Margin Bottom (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicTagsspacingMarginBottomMobile { get; }

		/// <summary>Margin Bottom (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicTagsspacingMarginBottomTablet { get; }

		/// <summary>Margin Left (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicTagsspacingMarginLeftDesktop { get; }

		/// <summary>Margin Left (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicTagsspacingMarginLeftMobile { get; }

		/// <summary>Margin Left (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicTagsspacingMarginLeftTablet { get; }

		/// <summary>Margin Right (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicTagsspacingMarginRightDesktop { get; }

		/// <summary>Margin Right (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicTagsspacingMarginRightMobile { get; }

		/// <summary>Margin Right (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicTagsspacingMarginRightTablet { get; }

		/// <summary>Margin Top (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicTagsspacingMarginTopDesktop { get; }

		/// <summary>Margin Top (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicTagsspacingMarginTopMobile { get; }

		/// <summary>Margin Top (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicTagsspacingMarginTopTablet { get; }
	}

	/// <summary>[Nubrik][Style][Theme Settings][Basic][Tags] Margin</summary>
	[PublishedModel("marginSettings3")]
	public partial class MarginSettings3 : PublishedElementModel, IMarginSettings3
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "marginSettings3";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<MarginSettings3, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public MarginSettings3(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Margin Bottom (Desktop): Specify the bottom margin for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicTagsspacingMarginBottomDesktop")]
		public virtual string BasicTagsspacingMarginBottomDesktop => GetBasicTagsspacingMarginBottomDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Bottom (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicTagsspacingMarginBottomDesktop(IMarginSettings3 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicTagsspacingMarginBottomDesktop");

		///<summary>
		/// Margin Bottom (Mobile): Specify the bottom margin for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicTagsspacingMarginBottomMobile")]
		public virtual string BasicTagsspacingMarginBottomMobile => GetBasicTagsspacingMarginBottomMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Bottom (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicTagsspacingMarginBottomMobile(IMarginSettings3 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicTagsspacingMarginBottomMobile");

		///<summary>
		/// Margin Bottom (Tablet): Specify the bottom margin for tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicTagsspacingMarginBottomTablet")]
		public virtual string BasicTagsspacingMarginBottomTablet => GetBasicTagsspacingMarginBottomTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Bottom (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicTagsspacingMarginBottomTablet(IMarginSettings3 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicTagsspacingMarginBottomTablet");

		///<summary>
		/// Margin Left (Desktop): Specify the left margin for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicTagsspacingMarginLeftDesktop")]
		public virtual string BasicTagsspacingMarginLeftDesktop => GetBasicTagsspacingMarginLeftDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Left (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicTagsspacingMarginLeftDesktop(IMarginSettings3 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicTagsspacingMarginLeftDesktop");

		///<summary>
		/// Margin Left (Mobile): Specify the left margin for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicTagsspacingMarginLeftMobile")]
		public virtual string BasicTagsspacingMarginLeftMobile => GetBasicTagsspacingMarginLeftMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Left (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicTagsspacingMarginLeftMobile(IMarginSettings3 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicTagsspacingMarginLeftMobile");

		///<summary>
		/// Margin Left (Tablet): Specify the left margin for tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicTagsspacingMarginLeftTablet")]
		public virtual string BasicTagsspacingMarginLeftTablet => GetBasicTagsspacingMarginLeftTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Left (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicTagsspacingMarginLeftTablet(IMarginSettings3 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicTagsspacingMarginLeftTablet");

		///<summary>
		/// Margin Right (Desktop): Specify the right margin for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicTagsspacingMarginRightDesktop")]
		public virtual string BasicTagsspacingMarginRightDesktop => GetBasicTagsspacingMarginRightDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Right (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicTagsspacingMarginRightDesktop(IMarginSettings3 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicTagsspacingMarginRightDesktop");

		///<summary>
		/// Margin Right (Mobile): Specify the right margin for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicTagsspacingMarginRightMobile")]
		public virtual string BasicTagsspacingMarginRightMobile => GetBasicTagsspacingMarginRightMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Right (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicTagsspacingMarginRightMobile(IMarginSettings3 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicTagsspacingMarginRightMobile");

		///<summary>
		/// Margin Right (Tablet): Specify the right margin for tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicTagsspacingMarginRightTablet")]
		public virtual string BasicTagsspacingMarginRightTablet => GetBasicTagsspacingMarginRightTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Right (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicTagsspacingMarginRightTablet(IMarginSettings3 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicTagsspacingMarginRightTablet");

		///<summary>
		/// Margin Top (Desktop): Specify the top margin for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicTagsspacingMarginTopDesktop")]
		public virtual string BasicTagsspacingMarginTopDesktop => GetBasicTagsspacingMarginTopDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Top (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicTagsspacingMarginTopDesktop(IMarginSettings3 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicTagsspacingMarginTopDesktop");

		///<summary>
		/// Margin Top (Mobile): Specify the top margin for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicTagsspacingMarginTopMobile")]
		public virtual string BasicTagsspacingMarginTopMobile => GetBasicTagsspacingMarginTopMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Top (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicTagsspacingMarginTopMobile(IMarginSettings3 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicTagsspacingMarginTopMobile");

		///<summary>
		/// Margin Top (Tablet): Specify the top margin for tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicTagsspacingMarginTopTablet")]
		public virtual string BasicTagsspacingMarginTopTablet => GetBasicTagsspacingMarginTopTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Top (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicTagsspacingMarginTopTablet(IMarginSettings3 that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicTagsspacingMarginTopTablet");
	}
}
