//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "nubrik_BasicBoxMarginSettings"
	/// <summary>[Nubrik][Style][Settings][Basic][Boxes] Margin </summary>
	public partial interface INubrik_BasicBoxMarginSettings : IPublishedElement
	{
		/// <summary>Margin Bottom (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesspacingMarginBottomDesktop { get; }

		/// <summary>Margin Bottom (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesspacingMarginBottomMobile { get; }

		/// <summary>Margin Bottom (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesspacingMarginBottomTablet { get; }

		/// <summary>Margin Left (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesspacingMarginLeftDesktop { get; }

		/// <summary>Margin Left (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesspacingMarginLeftMobile { get; }

		/// <summary>Margin Left (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesspacingMarginLeftTablet { get; }

		/// <summary>Margin Right (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesspacingMarginRightDesktop { get; }

		/// <summary>Margin Right (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesspacingMarginRightMobile { get; }

		/// <summary>Margin Right (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesspacingMarginRightTablet { get; }

		/// <summary>Margin Top (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesspacingMarginTopDesktop { get; }

		/// <summary>Margin Top (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesspacingMarginTopMobile { get; }

		/// <summary>Margin Top (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesspacingMarginTopTablet { get; }
	}

	/// <summary>[Nubrik][Style][Settings][Basic][Boxes] Margin </summary>
	[PublishedModel("nubrik_BasicBoxMarginSettings")]
	public partial class Nubrik_BasicBoxMarginSettings : PublishedElementModel, INubrik_BasicBoxMarginSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "nubrik_BasicBoxMarginSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<Nubrik_BasicBoxMarginSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Nubrik_BasicBoxMarginSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Margin Bottom (Desktop): Specify the bottom margin for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesspacingMarginBottomDesktop")]
		public virtual string BasicBoxesspacingMarginBottomDesktop => GetBasicBoxesspacingMarginBottomDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Bottom (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesspacingMarginBottomDesktop(INubrik_BasicBoxMarginSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesspacingMarginBottomDesktop");

		///<summary>
		/// Margin Bottom (Mobile): Specify the bottom margin for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesspacingMarginBottomMobile")]
		public virtual string BasicBoxesspacingMarginBottomMobile => GetBasicBoxesspacingMarginBottomMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Bottom (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesspacingMarginBottomMobile(INubrik_BasicBoxMarginSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesspacingMarginBottomMobile");

		///<summary>
		/// Margin Bottom (Tablet): Specify the bottom margin for tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesspacingMarginBottomTablet")]
		public virtual string BasicBoxesspacingMarginBottomTablet => GetBasicBoxesspacingMarginBottomTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Bottom (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesspacingMarginBottomTablet(INubrik_BasicBoxMarginSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesspacingMarginBottomTablet");

		///<summary>
		/// Margin Left (Desktop): Specify the left margin for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesspacingMarginLeftDesktop")]
		public virtual string BasicBoxesspacingMarginLeftDesktop => GetBasicBoxesspacingMarginLeftDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Left (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesspacingMarginLeftDesktop(INubrik_BasicBoxMarginSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesspacingMarginLeftDesktop");

		///<summary>
		/// Margin Left (Mobile): Specify the left margin for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesspacingMarginLeftMobile")]
		public virtual string BasicBoxesspacingMarginLeftMobile => GetBasicBoxesspacingMarginLeftMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Left (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesspacingMarginLeftMobile(INubrik_BasicBoxMarginSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesspacingMarginLeftMobile");

		///<summary>
		/// Margin Left (Tablet): Specify the left margin for tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesspacingMarginLeftTablet")]
		public virtual string BasicBoxesspacingMarginLeftTablet => GetBasicBoxesspacingMarginLeftTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Left (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesspacingMarginLeftTablet(INubrik_BasicBoxMarginSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesspacingMarginLeftTablet");

		///<summary>
		/// Margin Right (Desktop): Specify the right margin for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesspacingMarginRightDesktop")]
		public virtual string BasicBoxesspacingMarginRightDesktop => GetBasicBoxesspacingMarginRightDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Right (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesspacingMarginRightDesktop(INubrik_BasicBoxMarginSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesspacingMarginRightDesktop");

		///<summary>
		/// Margin Right (Mobile): Specify the right margin for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesspacingMarginRightMobile")]
		public virtual string BasicBoxesspacingMarginRightMobile => GetBasicBoxesspacingMarginRightMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Right (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesspacingMarginRightMobile(INubrik_BasicBoxMarginSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesspacingMarginRightMobile");

		///<summary>
		/// Margin Right (Tablet): Specify the right margin for tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesspacingMarginRightTablet")]
		public virtual string BasicBoxesspacingMarginRightTablet => GetBasicBoxesspacingMarginRightTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Right (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesspacingMarginRightTablet(INubrik_BasicBoxMarginSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesspacingMarginRightTablet");

		///<summary>
		/// Margin Top (Desktop): Specify the top margin for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesspacingMarginTopDesktop")]
		public virtual string BasicBoxesspacingMarginTopDesktop => GetBasicBoxesspacingMarginTopDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Top (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesspacingMarginTopDesktop(INubrik_BasicBoxMarginSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesspacingMarginTopDesktop");

		///<summary>
		/// Margin Top (Mobile): Specify the top margin for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesspacingMarginTopMobile")]
		public virtual string BasicBoxesspacingMarginTopMobile => GetBasicBoxesspacingMarginTopMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Top (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesspacingMarginTopMobile(INubrik_BasicBoxMarginSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesspacingMarginTopMobile");

		///<summary>
		/// Margin Top (Tablet): Specify the top margin for tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesspacingMarginTopTablet")]
		public virtual string BasicBoxesspacingMarginTopTablet => GetBasicBoxesspacingMarginTopTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Top (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesspacingMarginTopTablet(INubrik_BasicBoxMarginSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesspacingMarginTopTablet");
	}
}
