//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "nubrik_BasicBoxesBackgroundOverlaySettings"
	/// <summary>[Nubrik][Style][Settings][Basic][Boxes] Background Overlay</summary>
	public partial interface INubrik_BasicBoxesBackgroundOverlaySettings : IPublishedElement
	{
		/// <summary>Overlay Angle (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlayAngleDesktop { get; }

		/// <summary>Overlay Angle (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlayAngleMobile { get; }

		/// <summary>Overlay Angle (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlayAngleTablet { get; }

		/// <summary>Overlay Opacity (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlayOpacityDesktop { get; }

		/// <summary>Overlay Opacity (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlayOpacityMobile { get; }

		/// <summary>Overlay Opacity (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlayOpacityTablet { get; }

		/// <summary>Overlay Primary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlayPrimaryColor { get; }

		/// <summary>Primary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlayPrimaryLocationDesktop { get; }

		/// <summary>Primary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlayPrimaryLocationMobile { get; }

		/// <summary>Primary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlayPrimaryLocationTablet { get; }

		/// <summary>Overlay Secondary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlaySecondaryColor { get; }

		/// <summary>Secondary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlaySecondaryLocationDesktop { get; }

		/// <summary>Secondary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlaySecondaryLocationMobile { get; }

		/// <summary>Secondary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlaySecondaryLocationTablet { get; }

		/// <summary>Overlay Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string BasicBoxesBackgroundOverlayType { get; }

		/// <summary>Background OverlayType - Gradient</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string NuignorebasicBoxesBackgroundOverlayTypeGradient { get; }

		/// <summary>Background OverlayType - Solid</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string NuignorebasicBoxesBackgroundOverlayTypeSolid { get; }
	}

	/// <summary>[Nubrik][Style][Settings][Basic][Boxes] Background Overlay</summary>
	[PublishedModel("nubrik_BasicBoxesBackgroundOverlaySettings")]
	public partial class Nubrik_BasicBoxesBackgroundOverlaySettings : PublishedElementModel, INubrik_BasicBoxesBackgroundOverlaySettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "nubrik_BasicBoxesBackgroundOverlaySettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<Nubrik_BasicBoxesBackgroundOverlaySettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Nubrik_BasicBoxesBackgroundOverlaySettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Overlay Angle (Desktop): Specify the angle of the background overlay gradient for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlayAngleDesktop")]
		public virtual string BasicBoxesBackgroundOverlayAngleDesktop => GetBasicBoxesBackgroundOverlayAngleDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Angle (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlayAngleDesktop(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlayAngleDesktop");

		///<summary>
		/// Overlay Angle (Mobile): Specify the angle of the background overlay gradient for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlayAngleMobile")]
		public virtual string BasicBoxesBackgroundOverlayAngleMobile => GetBasicBoxesBackgroundOverlayAngleMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Angle (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlayAngleMobile(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlayAngleMobile");

		///<summary>
		/// Overlay Angle (Tablet): Specify the angle of the background overlay gradient for tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlayAngleTablet")]
		public virtual string BasicBoxesBackgroundOverlayAngleTablet => GetBasicBoxesBackgroundOverlayAngleTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Angle (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlayAngleTablet(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlayAngleTablet");

		///<summary>
		/// Overlay Opacity (Desktop): Set the transparency level of the background overlay for desktop devices (0–100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlayOpacityDesktop")]
		public virtual string BasicBoxesBackgroundOverlayOpacityDesktop => GetBasicBoxesBackgroundOverlayOpacityDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Opacity (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlayOpacityDesktop(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlayOpacityDesktop");

		///<summary>
		/// Overlay Opacity (Mobile): Set the transparency level of the background overlay for mobile devices (0–100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlayOpacityMobile")]
		public virtual string BasicBoxesBackgroundOverlayOpacityMobile => GetBasicBoxesBackgroundOverlayOpacityMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Opacity (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlayOpacityMobile(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlayOpacityMobile");

		///<summary>
		/// Overlay Opacity (Tablet): Set the transparency level of the background overlay for tablet devices (0–100).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlayOpacityTablet")]
		public virtual string BasicBoxesBackgroundOverlayOpacityTablet => GetBasicBoxesBackgroundOverlayOpacityTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Opacity (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlayOpacityTablet(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlayOpacityTablet");

		///<summary>
		/// Overlay Primary Color: Select the primary color used in the background overlay.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlayPrimaryColor")]
		public virtual string BasicBoxesBackgroundOverlayPrimaryColor => GetBasicBoxesBackgroundOverlayPrimaryColor(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Primary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlayPrimaryColor(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlayPrimaryColor");

		///<summary>
		/// Primary Color Position (Desktop): Specify the position of the primary overlay color stop for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlayPrimaryLocationDesktop")]
		public virtual string BasicBoxesBackgroundOverlayPrimaryLocationDesktop => GetBasicBoxesBackgroundOverlayPrimaryLocationDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Primary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlayPrimaryLocationDesktop(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlayPrimaryLocationDesktop");

		///<summary>
		/// Primary Color Position (Mobile): Specify the position of the primary overlay color stop for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlayPrimaryLocationMobile")]
		public virtual string BasicBoxesBackgroundOverlayPrimaryLocationMobile => GetBasicBoxesBackgroundOverlayPrimaryLocationMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Primary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlayPrimaryLocationMobile(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlayPrimaryLocationMobile");

		///<summary>
		/// Primary Color Position (Tablet): Specify the position of the primary overlay color stop for tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlayPrimaryLocationTablet")]
		public virtual string BasicBoxesBackgroundOverlayPrimaryLocationTablet => GetBasicBoxesBackgroundOverlayPrimaryLocationTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Primary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlayPrimaryLocationTablet(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlayPrimaryLocationTablet");

		///<summary>
		/// Overlay Secondary Color: Select the secondary color used in the background overlay gradient.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlaySecondaryColor")]
		public virtual string BasicBoxesBackgroundOverlaySecondaryColor => GetBasicBoxesBackgroundOverlaySecondaryColor(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Secondary Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlaySecondaryColor(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlaySecondaryColor");

		///<summary>
		/// Secondary Color Position (Desktop): Specify the position of the secondary overlay color stop for desktop devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlaySecondaryLocationDesktop")]
		public virtual string BasicBoxesBackgroundOverlaySecondaryLocationDesktop => GetBasicBoxesBackgroundOverlaySecondaryLocationDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Secondary Color Position (Desktop)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlaySecondaryLocationDesktop(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlaySecondaryLocationDesktop");

		///<summary>
		/// Secondary Color Position (Mobile): Specify the position of the secondary overlay color stop for mobile devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlaySecondaryLocationMobile")]
		public virtual string BasicBoxesBackgroundOverlaySecondaryLocationMobile => GetBasicBoxesBackgroundOverlaySecondaryLocationMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Secondary Color Position (Mobile)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlaySecondaryLocationMobile(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlaySecondaryLocationMobile");

		///<summary>
		/// Secondary Color Position (Tablet): Specify the position of the secondary overlay color stop for tablet devices.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlaySecondaryLocationTablet")]
		public virtual string BasicBoxesBackgroundOverlaySecondaryLocationTablet => GetBasicBoxesBackgroundOverlaySecondaryLocationTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Secondary Color Position (Tablet)</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlaySecondaryLocationTablet(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlaySecondaryLocationTablet");

		///<summary>
		/// Overlay Type: Select the type of background overlay to apply (for example, Solid or Gradient).
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBoxesBackgroundOverlayType")]
		public virtual string BasicBoxesBackgroundOverlayType => GetBasicBoxesBackgroundOverlayType(this, _publishedValueFallback);

		/// <summary>Static getter for Overlay Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetBasicBoxesBackgroundOverlayType(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "basicBoxesBackgroundOverlayType");

		///<summary>
		/// Background OverlayType - Gradient: The following settings apply only when the Background Overlay Type is set to Gradient.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuignorebasicBoxesBackgroundOverlayTypeGradient")]
		public virtual string NuignorebasicBoxesBackgroundOverlayTypeGradient => GetNuignorebasicBoxesBackgroundOverlayTypeGradient(this, _publishedValueFallback);

		/// <summary>Static getter for Background OverlayType - Gradient</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetNuignorebasicBoxesBackgroundOverlayTypeGradient(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "nuignorebasicBoxesBackgroundOverlayTypeGradient");

		///<summary>
		/// Background OverlayType - Solid: The following settings apply only when the Background Overlay Type is set to Solid.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuignorebasicBoxesBackgroundOverlayTypeSolid")]
		public virtual string NuignorebasicBoxesBackgroundOverlayTypeSolid => GetNuignorebasicBoxesBackgroundOverlayTypeSolid(this, _publishedValueFallback);

		/// <summary>Static getter for Background OverlayType - Solid</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetNuignorebasicBoxesBackgroundOverlayTypeSolid(INubrik_BasicBoxesBackgroundOverlaySettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "nuignorebasicBoxesBackgroundOverlayTypeSolid");
	}
}
