//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>[Nubrik][Settings] Paragraph</summary>
	[PublishedModel("paragraphElementSettings")]
	public partial class ParagraphElementSettings : PublishedElementModel, IAdvancedSettings, IAnimationSettings, IBasicBackgroundTypeNormalClassicSettings, IBasicBorderSettings, IBasicBoxshadowSettings, IBasicGradientBackgroundTypeSettings, IBasicTextColorSettings, IFullWidthSettings, IHoverBackgroundTypeGradientSettings, IHoverBackgroundTypeNormalClassicSettings, IHoverBorderSettings, IHoverBoxshadowSettings, IHoverTextColorSettings, IMarginSettings, IPaddingSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "paragraphElementSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<ParagraphElementSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ParagraphElementSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Class Name: Specify one or more custom CSS class names to apply additional styling or behavior.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("advancedclassName")]
		public virtual string AdvancedclassName => global::Umbraco.Cms.Web.Common.PublishedModels.AdvancedSettings.GetAdvancedclassName(this, _publishedValueFallback);

		///<summary>
		/// css: Enter custom CSS rules to apply additional styling
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("advancedcss")]
		public virtual string Advancedcss => global::Umbraco.Cms.Web.Common.PublishedModels.AdvancedSettings.GetAdvancedcss(this, _publishedValueFallback);

		///<summary>
		/// id: Specify a unique HTML ID. Use this to target the element with CSS, JavaScript, or anchor links.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("advancedid")]
		public virtual string Advancedid => global::Umbraco.Cms.Web.Common.PublishedModels.AdvancedSettings.GetAdvancedid(this, _publishedValueFallback);

		///<summary>
		/// Animation: Animation Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("animation")]
		public virtual string Animation => global::Umbraco.Cms.Web.Common.PublishedModels.AnimationSettings.GetAnimation(this, _publishedValueFallback);

		///<summary>
		/// Animation Delay: Delay
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("animationDelay")]
		public virtual string AnimationDelay => global::Umbraco.Cms.Web.Common.PublishedModels.AnimationSettings.GetAnimationDelay(this, _publishedValueFallback);

		///<summary>
		/// Animation Repeat: Repeat
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("animationRepeat")]
		public virtual string AnimationRepeat => global::Umbraco.Cms.Web.Common.PublishedModels.AnimationSettings.GetAnimationRepeat(this, _publishedValueFallback);

		///<summary>
		/// Animation Speed: Speed
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("animationSpeed")]
		public virtual string AnimationSpeed => global::Umbraco.Cms.Web.Common.PublishedModels.AnimationSettings.GetAnimationSpeed(this, _publishedValueFallback);

		///<summary>
		/// Background Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBackgroundColor")]
		public virtual string BasicBackgroundColor => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBackgroundTypeNormalClassicSettings.GetBasicBackgroundColor(this, _publishedValueFallback);

		///<summary>
		/// Background Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBackgroundType")]
		public virtual string BasicBackgroundType => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBackgroundTypeNormalClassicSettings.GetBasicBackgroundType(this, _publishedValueFallback);

		///<summary>
		/// backgroundType - classic
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuignoreBasicBackgroundTypeClassic")]
		public virtual string NuignoreBasicBackgroundTypeClassic => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBackgroundTypeNormalClassicSettings.GetNuignoreBasicBackgroundTypeClassic(this, _publishedValueFallback);

		///<summary>
		/// Border Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBorderColor")]
		public virtual string BasicBorderColor => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicBorderColor(this, _publishedValueFallback);

		///<summary>
		/// Border Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBorderType")]
		public virtual string BasicBorderType => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicBorderType(this, _publishedValueFallback);

		///<summary>
		/// Border Width Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBorderWidthDesktop")]
		public virtual string BasicBorderWidthDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicBorderWidthDesktop(this, _publishedValueFallback);

		///<summary>
		/// Border Width Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBorderWidthMobile")]
		public virtual string BasicBorderWidthMobile => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicBorderWidthMobile(this, _publishedValueFallback);

		///<summary>
		/// Border Width Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBorderWidthTablet")]
		public virtual string BasicBorderWidthTablet => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicBorderWidthTablet(this, _publishedValueFallback);

		///<summary>
		/// Radius Bottom Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicRadiusBottomDesktop")]
		public virtual string BasicRadiusBottomDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicRadiusBottomDesktop(this, _publishedValueFallback);

		///<summary>
		/// Radius Bottom Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicRadiusBottomMobile")]
		public virtual string BasicRadiusBottomMobile => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicRadiusBottomMobile(this, _publishedValueFallback);

		///<summary>
		/// Radius Bottom Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicRadiusBottomTablet")]
		public virtual string BasicRadiusBottomTablet => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicRadiusBottomTablet(this, _publishedValueFallback);

		///<summary>
		/// Radius Left Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicRadiusLeftDesktop")]
		public virtual string BasicRadiusLeftDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicRadiusLeftDesktop(this, _publishedValueFallback);

		///<summary>
		/// Radius Left Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicRadiusLeftMobile")]
		public virtual string BasicRadiusLeftMobile => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicRadiusLeftMobile(this, _publishedValueFallback);

		///<summary>
		/// Radius Left Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicRadiusLeftTablet")]
		public virtual string BasicRadiusLeftTablet => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicRadiusLeftTablet(this, _publishedValueFallback);

		///<summary>
		/// Radius Right Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicRadiusRightDesktop")]
		public virtual string BasicRadiusRightDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicRadiusRightDesktop(this, _publishedValueFallback);

		///<summary>
		/// Radius Right Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicRadiusRightMobile")]
		public virtual string BasicRadiusRightMobile => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicRadiusRightMobile(this, _publishedValueFallback);

		///<summary>
		/// Radius Right Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicRadiusRightTablet")]
		public virtual string BasicRadiusRightTablet => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicRadiusRightTablet(this, _publishedValueFallback);

		///<summary>
		/// Radius Top Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicRadiusTopDesktop")]
		public virtual string BasicRadiusTopDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicRadiusTopDesktop(this, _publishedValueFallback);

		///<summary>
		/// Radius Top Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicRadiusTopMobile")]
		public virtual string BasicRadiusTopMobile => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicRadiusTopMobile(this, _publishedValueFallback);

		///<summary>
		/// Radius Top Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicRadiusTopTablet")]
		public virtual string BasicRadiusTopTablet => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBorderSettings.GetBasicRadiusTopTablet(this, _publishedValueFallback);

		///<summary>
		/// Box shadow Blur: Box shadow Blur
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBorderBlur")]
		public virtual string BasicBorderBlur => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBoxshadowSettings.GetBasicBorderBlur(this, _publishedValueFallback);

		///<summary>
		/// Box shadow Horizontal: Box shadow Horizontal
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBorderHorizontal")]
		public virtual string BasicBorderHorizontal => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBoxshadowSettings.GetBasicBorderHorizontal(this, _publishedValueFallback);

		///<summary>
		/// Box shadow Position: Box shadow Position
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBorderPosition")]
		public virtual string BasicBorderPosition => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBoxshadowSettings.GetBasicBorderPosition(this, _publishedValueFallback);

		///<summary>
		/// Shadow Color: Box shadow color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBordershadowColor")]
		public virtual string BasicBordershadowColor => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBoxshadowSettings.GetBasicBordershadowColor(this, _publishedValueFallback);

		///<summary>
		/// Box shadow Spread: Box shadow Spread
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBorderSpread")]
		public virtual string BasicBorderSpread => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBoxshadowSettings.GetBasicBorderSpread(this, _publishedValueFallback);

		///<summary>
		/// Box shadow Vertical: Box shadow Vertical
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBorderVertical")]
		public virtual string BasicBorderVertical => global::Umbraco.Cms.Web.Common.PublishedModels.BasicBoxshadowSettings.GetBasicBorderVertical(this, _publishedValueFallback);

		///<summary>
		/// Angle Desktop: Gradient Angle Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBackgroundGradientAngleDesktop")]
		public virtual string BasicBackgroundGradientAngleDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.BasicGradientBackgroundTypeSettings.GetBasicBackgroundGradientAngleDesktop(this, _publishedValueFallback);

		///<summary>
		/// Angle Mobile: Gradient Angle Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBackgroundGradientAngleMobile")]
		public virtual string BasicBackgroundGradientAngleMobile => global::Umbraco.Cms.Web.Common.PublishedModels.BasicGradientBackgroundTypeSettings.GetBasicBackgroundGradientAngleMobile(this, _publishedValueFallback);

		///<summary>
		/// Angle Tablet: Gradient Angle Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBackgroundGradientAngleTablet")]
		public virtual string BasicBackgroundGradientAngleTablet => global::Umbraco.Cms.Web.Common.PublishedModels.BasicGradientBackgroundTypeSettings.GetBasicBackgroundGradientAngleTablet(this, _publishedValueFallback);

		///<summary>
		/// Primary Color: Background Gradient Primary Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBackgroundGradientPrimaryColor")]
		public virtual string BasicBackgroundGradientPrimaryColor => global::Umbraco.Cms.Web.Common.PublishedModels.BasicGradientBackgroundTypeSettings.GetBasicBackgroundGradientPrimaryColor(this, _publishedValueFallback);

		///<summary>
		/// Location Desktop: Background Gradient Primary Location Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBackgroundGradientPrimaryLocationDesktop")]
		public virtual string BasicBackgroundGradientPrimaryLocationDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.BasicGradientBackgroundTypeSettings.GetBasicBackgroundGradientPrimaryLocationDesktop(this, _publishedValueFallback);

		///<summary>
		/// Location Mobile: Background Gradient Primary Location Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBackgroundGradientPrimaryLocationMobile")]
		public virtual string BasicBackgroundGradientPrimaryLocationMobile => global::Umbraco.Cms.Web.Common.PublishedModels.BasicGradientBackgroundTypeSettings.GetBasicBackgroundGradientPrimaryLocationMobile(this, _publishedValueFallback);

		///<summary>
		/// Location Tablet: Background Gradient Primary Location Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBackgroundGradientPrimaryLocationTablet")]
		public virtual string BasicBackgroundGradientPrimaryLocationTablet => global::Umbraco.Cms.Web.Common.PublishedModels.BasicGradientBackgroundTypeSettings.GetBasicBackgroundGradientPrimaryLocationTablet(this, _publishedValueFallback);

		///<summary>
		/// Secondary color: Background Gradient Secondary Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBackgroundGradientSecondaryColor")]
		public virtual string BasicBackgroundGradientSecondaryColor => global::Umbraco.Cms.Web.Common.PublishedModels.BasicGradientBackgroundTypeSettings.GetBasicBackgroundGradientSecondaryColor(this, _publishedValueFallback);

		///<summary>
		/// Location: Background Gradient Secondary Location Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBackgroundGradientSecondaryLocationDesktop")]
		public virtual string BasicBackgroundGradientSecondaryLocationDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.BasicGradientBackgroundTypeSettings.GetBasicBackgroundGradientSecondaryLocationDesktop(this, _publishedValueFallback);

		///<summary>
		/// Location: Background Gradient Secondary Location Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBackgroundGradientSecondaryLocationMobile")]
		public virtual string BasicBackgroundGradientSecondaryLocationMobile => global::Umbraco.Cms.Web.Common.PublishedModels.BasicGradientBackgroundTypeSettings.GetBasicBackgroundGradientSecondaryLocationMobile(this, _publishedValueFallback);

		///<summary>
		/// Location: Background Gradient Secondary Location Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBackgroundGradientSecondaryLocationTablet")]
		public virtual string BasicBackgroundGradientSecondaryLocationTablet => global::Umbraco.Cms.Web.Common.PublishedModels.BasicGradientBackgroundTypeSettings.GetBasicBackgroundGradientSecondaryLocationTablet(this, _publishedValueFallback);

		///<summary>
		/// Type: Gradient Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicBackgroundGradientType")]
		public virtual string BasicBackgroundGradientType => global::Umbraco.Cms.Web.Common.PublishedModels.BasicGradientBackgroundTypeSettings.GetBasicBackgroundGradientType(this, _publishedValueFallback);

		///<summary>
		/// BackgroundType-Gradient
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuignoreBasicBackgroundTypeGradient")]
		public virtual string NuignoreBasicBackgroundTypeGradient => global::Umbraco.Cms.Web.Common.PublishedModels.BasicGradientBackgroundTypeSettings.GetNuignoreBasicBackgroundTypeGradient(this, _publishedValueFallback);

		///<summary>
		/// Basic Text Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("basicCommonTextColor")]
		public virtual string BasicCommonTextColor => global::Umbraco.Cms.Web.Common.PublishedModels.BasicTextColorSettings.GetBasicCommonTextColor(this, _publishedValueFallback);

		///<summary>
		/// Full Width Toggle: Enable to extend the element to span the full width of the viewport.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[ImplementPropertyType("fullWidthToggle")]
		public virtual bool FullWidthToggle => global::Umbraco.Cms.Web.Common.PublishedModels.FullWidthSettings.GetFullWidthToggle(this, _publishedValueFallback);

		///<summary>
		/// Angle Desktop: Gradient Angle Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientAngleDesktop")]
		public virtual string HoverBackgroundGradientAngleDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeGradientSettings.GetHoverBackgroundGradientAngleDesktop(this, _publishedValueFallback);

		///<summary>
		/// Angle Mobile: Gradient Angle Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientAngleMobile")]
		public virtual string HoverBackgroundGradientAngleMobile => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeGradientSettings.GetHoverBackgroundGradientAngleMobile(this, _publishedValueFallback);

		///<summary>
		/// Angle Tablet: Gradient Angle Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientAngleTablet")]
		public virtual string HoverBackgroundGradientAngleTablet => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeGradientSettings.GetHoverBackgroundGradientAngleTablet(this, _publishedValueFallback);

		///<summary>
		/// Primary Color: Background Gradient Primary Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientPrimaryColor")]
		public virtual string HoverBackgroundGradientPrimaryColor => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeGradientSettings.GetHoverBackgroundGradientPrimaryColor(this, _publishedValueFallback);

		///<summary>
		/// Location Desktop: Background Gradient Primary Location Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientPrimaryLocationDesktop")]
		public virtual string HoverBackgroundGradientPrimaryLocationDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeGradientSettings.GetHoverBackgroundGradientPrimaryLocationDesktop(this, _publishedValueFallback);

		///<summary>
		/// Location Mobile: Background Gradient Primary Location Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientPrimaryLocationMobile")]
		public virtual string HoverBackgroundGradientPrimaryLocationMobile => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeGradientSettings.GetHoverBackgroundGradientPrimaryLocationMobile(this, _publishedValueFallback);

		///<summary>
		/// Location Tablet: Background Gradient Primary Location Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientPrimaryLocationTablet")]
		public virtual string HoverBackgroundGradientPrimaryLocationTablet => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeGradientSettings.GetHoverBackgroundGradientPrimaryLocationTablet(this, _publishedValueFallback);

		///<summary>
		/// Secondary color: Background Gradient Secondary Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientSecondaryColor")]
		public virtual string HoverBackgroundGradientSecondaryColor => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeGradientSettings.GetHoverBackgroundGradientSecondaryColor(this, _publishedValueFallback);

		///<summary>
		/// Location: Background Gradient Secondary Location Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientSecondaryLocationDesktop")]
		public virtual string HoverBackgroundGradientSecondaryLocationDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeGradientSettings.GetHoverBackgroundGradientSecondaryLocationDesktop(this, _publishedValueFallback);

		///<summary>
		/// Location: Background Gradient Secondary Location Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientSecondaryLocationMobile")]
		public virtual string HoverBackgroundGradientSecondaryLocationMobile => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeGradientSettings.GetHoverBackgroundGradientSecondaryLocationMobile(this, _publishedValueFallback);

		///<summary>
		/// Location: Background Gradient Secondary Location Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientSecondaryLocationTablet")]
		public virtual string HoverBackgroundGradientSecondaryLocationTablet => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeGradientSettings.GetHoverBackgroundGradientSecondaryLocationTablet(this, _publishedValueFallback);

		///<summary>
		/// Type: Gradient Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundGradientType")]
		public virtual string HoverBackgroundGradientType => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeGradientSettings.GetHoverBackgroundGradientType(this, _publishedValueFallback);

		///<summary>
		/// BackgroundType-Gradient
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuignoreHoverBackgroundTypeGradient")]
		public virtual string NuignoreHoverBackgroundTypeGradient => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeGradientSettings.GetNuignoreHoverBackgroundTypeGradient(this, _publishedValueFallback);

		///<summary>
		/// Background Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundColor")]
		public virtual string HoverBackgroundColor => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeNormalClassicSettings.GetHoverBackgroundColor(this, _publishedValueFallback);

		///<summary>
		/// Background Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBackgroundType")]
		public virtual string HoverBackgroundType => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeNormalClassicSettings.GetHoverBackgroundType(this, _publishedValueFallback);

		///<summary>
		/// backgroundType - classic
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("nuignoreHoverBackgroundTypeClassic")]
		public virtual string NuignoreHoverBackgroundTypeClassic => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBackgroundTypeNormalClassicSettings.GetNuignoreHoverBackgroundTypeClassic(this, _publishedValueFallback);

		///<summary>
		/// Border Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBorderColor")]
		public virtual string HoverBorderColor => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverBorderColor(this, _publishedValueFallback);

		///<summary>
		/// Border Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBorderType")]
		public virtual string HoverBorderType => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverBorderType(this, _publishedValueFallback);

		///<summary>
		/// Border Width Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBorderWidthDesktop")]
		public virtual string HoverBorderWidthDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverBorderWidthDesktop(this, _publishedValueFallback);

		///<summary>
		/// Border Width Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBorderWidthMobile")]
		public virtual string HoverBorderWidthMobile => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverBorderWidthMobile(this, _publishedValueFallback);

		///<summary>
		/// Border Width Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBorderWidthTablet")]
		public virtual string HoverBorderWidthTablet => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverBorderWidthTablet(this, _publishedValueFallback);

		///<summary>
		/// Radius Bottom Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverRadiusBottomDesktop")]
		public virtual string HoverRadiusBottomDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverRadiusBottomDesktop(this, _publishedValueFallback);

		///<summary>
		/// Radius Bottom Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverRadiusBottomMobile")]
		public virtual string HoverRadiusBottomMobile => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverRadiusBottomMobile(this, _publishedValueFallback);

		///<summary>
		/// Radius Bottom Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverRadiusBottomTablet")]
		public virtual string HoverRadiusBottomTablet => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverRadiusBottomTablet(this, _publishedValueFallback);

		///<summary>
		/// Radius Left Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverRadiusLeftDesktop")]
		public virtual string HoverRadiusLeftDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverRadiusLeftDesktop(this, _publishedValueFallback);

		///<summary>
		/// Radius Left Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverRadiusLeftMobile")]
		public virtual string HoverRadiusLeftMobile => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverRadiusLeftMobile(this, _publishedValueFallback);

		///<summary>
		/// Radius Left Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverRadiusLeftTablet")]
		public virtual string HoverRadiusLeftTablet => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverRadiusLeftTablet(this, _publishedValueFallback);

		///<summary>
		/// Radius Right Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverRadiusRightDesktop")]
		public virtual string HoverRadiusRightDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverRadiusRightDesktop(this, _publishedValueFallback);

		///<summary>
		/// Radius Right Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverRadiusRightMobile")]
		public virtual string HoverRadiusRightMobile => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverRadiusRightMobile(this, _publishedValueFallback);

		///<summary>
		/// Radius Right Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverRadiusRightTablet")]
		public virtual string HoverRadiusRightTablet => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverRadiusRightTablet(this, _publishedValueFallback);

		///<summary>
		/// Radius Top Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverRadiusTopDesktop")]
		public virtual string HoverRadiusTopDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverRadiusTopDesktop(this, _publishedValueFallback);

		///<summary>
		/// Radius Top Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverRadiusTopMobile")]
		public virtual string HoverRadiusTopMobile => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverRadiusTopMobile(this, _publishedValueFallback);

		///<summary>
		/// Radius Top Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverRadiusTopTablet")]
		public virtual string HoverRadiusTopTablet => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBorderSettings.GetHoverRadiusTopTablet(this, _publishedValueFallback);

		///<summary>
		/// Box shadow Blur: Box shadow Blur
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBorderBlur")]
		public virtual string HoverBorderBlur => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBoxshadowSettings.GetHoverBorderBlur(this, _publishedValueFallback);

		///<summary>
		/// Box shadow Horizontal: Box shadow Horizontal
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBorderHorizontal")]
		public virtual string HoverBorderHorizontal => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBoxshadowSettings.GetHoverBorderHorizontal(this, _publishedValueFallback);

		///<summary>
		/// Box shadow Position: Box shadow Position
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBorderPosition")]
		public virtual string HoverBorderPosition => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBoxshadowSettings.GetHoverBorderPosition(this, _publishedValueFallback);

		///<summary>
		/// Shadow Color: Box shadow color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBordershadowColor")]
		public virtual string HoverBordershadowColor => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBoxshadowSettings.GetHoverBordershadowColor(this, _publishedValueFallback);

		///<summary>
		/// Box shadow Spread: Box shadow Spread
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBorderSpread")]
		public virtual string HoverBorderSpread => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBoxshadowSettings.GetHoverBorderSpread(this, _publishedValueFallback);

		///<summary>
		/// Box shadow Vertical: Box shadow Vertical
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverBorderVertical")]
		public virtual string HoverBorderVertical => global::Umbraco.Cms.Web.Common.PublishedModels.HoverBoxshadowSettings.GetHoverBorderVertical(this, _publishedValueFallback);

		///<summary>
		/// Hover Text Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("hoverCommonTextColor")]
		public virtual string HoverCommonTextColor => global::Umbraco.Cms.Web.Common.PublishedModels.HoverTextColorSettings.GetHoverCommonTextColor(this, _publishedValueFallback);

		///<summary>
		/// Margin Bottom Desktop: Spacing Margin Bottom Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingMarginBottomDesktop")]
		public virtual string SpacingMarginBottomDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.MarginSettings.GetSpacingMarginBottomDesktop(this, _publishedValueFallback);

		///<summary>
		/// Margin Bottom Mobile: Spacing Margin Bottom Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingMarginBottomMobile")]
		public virtual string SpacingMarginBottomMobile => global::Umbraco.Cms.Web.Common.PublishedModels.MarginSettings.GetSpacingMarginBottomMobile(this, _publishedValueFallback);

		///<summary>
		/// Margin Bottom Tablet: Spacing Margin Bottom Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingMarginBottomTablet")]
		public virtual string SpacingMarginBottomTablet => global::Umbraco.Cms.Web.Common.PublishedModels.MarginSettings.GetSpacingMarginBottomTablet(this, _publishedValueFallback);

		///<summary>
		/// Margin Left Desktop: Spacing Margin Left Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingMarginLeftDesktop")]
		public virtual string SpacingMarginLeftDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.MarginSettings.GetSpacingMarginLeftDesktop(this, _publishedValueFallback);

		///<summary>
		/// Margin Left Mobile: Spacing Margin Left Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingMarginLeftMobile")]
		public virtual string SpacingMarginLeftMobile => global::Umbraco.Cms.Web.Common.PublishedModels.MarginSettings.GetSpacingMarginLeftMobile(this, _publishedValueFallback);

		///<summary>
		/// Margin Left Tablet: Spacing Margin Left Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingMarginLeftTablet")]
		public virtual string SpacingMarginLeftTablet => global::Umbraco.Cms.Web.Common.PublishedModels.MarginSettings.GetSpacingMarginLeftTablet(this, _publishedValueFallback);

		///<summary>
		/// Margin Right Desktop: Spacing Margin Right Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingMarginRightDesktop")]
		public virtual string SpacingMarginRightDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.MarginSettings.GetSpacingMarginRightDesktop(this, _publishedValueFallback);

		///<summary>
		/// Margin Right Mobile: Spacing Margin Right Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingMarginRightMobile")]
		public virtual string SpacingMarginRightMobile => global::Umbraco.Cms.Web.Common.PublishedModels.MarginSettings.GetSpacingMarginRightMobile(this, _publishedValueFallback);

		///<summary>
		/// Margin Right Tablet: Spacing Margin Right Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingMarginRightTablet")]
		public virtual string SpacingMarginRightTablet => global::Umbraco.Cms.Web.Common.PublishedModels.MarginSettings.GetSpacingMarginRightTablet(this, _publishedValueFallback);

		///<summary>
		/// Margin Top Desktop: Spacing Margin Top Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingMarginTopDesktop")]
		public virtual string SpacingMarginTopDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.MarginSettings.GetSpacingMarginTopDesktop(this, _publishedValueFallback);

		///<summary>
		/// Margin Top Mobile: Spacing Margin Top Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingMarginTopMobile")]
		public virtual string SpacingMarginTopMobile => global::Umbraco.Cms.Web.Common.PublishedModels.MarginSettings.GetSpacingMarginTopMobile(this, _publishedValueFallback);

		///<summary>
		/// Margin Top Tablet: Spacing Margin Top Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingMarginTopTablet")]
		public virtual string SpacingMarginTopTablet => global::Umbraco.Cms.Web.Common.PublishedModels.MarginSettings.GetSpacingMarginTopTablet(this, _publishedValueFallback);

		///<summary>
		/// Padding Bottom Desktop: Spacing Padding Bottom Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingPaddingBottomDesktop")]
		public virtual string SpacingPaddingBottomDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.PaddingSettings.GetSpacingPaddingBottomDesktop(this, _publishedValueFallback);

		///<summary>
		/// Padding Bottom Mobile: Spacing Padding Bottom Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingPaddingBottomMobile")]
		public virtual string SpacingPaddingBottomMobile => global::Umbraco.Cms.Web.Common.PublishedModels.PaddingSettings.GetSpacingPaddingBottomMobile(this, _publishedValueFallback);

		///<summary>
		/// Padding Bottom Tablet: Spacing Padding Bottom Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingPaddingBottomTablet")]
		public virtual string SpacingPaddingBottomTablet => global::Umbraco.Cms.Web.Common.PublishedModels.PaddingSettings.GetSpacingPaddingBottomTablet(this, _publishedValueFallback);

		///<summary>
		/// Padding Left Desktop: Spacing Padding Left Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingPaddingLeftDesktop")]
		public virtual string SpacingPaddingLeftDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.PaddingSettings.GetSpacingPaddingLeftDesktop(this, _publishedValueFallback);

		///<summary>
		/// Padding Left Mobile: Spacing Padding Left Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingPaddingLeftMobile")]
		public virtual string SpacingPaddingLeftMobile => global::Umbraco.Cms.Web.Common.PublishedModels.PaddingSettings.GetSpacingPaddingLeftMobile(this, _publishedValueFallback);

		///<summary>
		/// Padding Left Tablet: Spacing Padding Left Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingPaddingLeftTablet")]
		public virtual string SpacingPaddingLeftTablet => global::Umbraco.Cms.Web.Common.PublishedModels.PaddingSettings.GetSpacingPaddingLeftTablet(this, _publishedValueFallback);

		///<summary>
		/// Padding Right Desktop: Spacing Padding Right Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingPaddingRightDesktop")]
		public virtual string SpacingPaddingRightDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.PaddingSettings.GetSpacingPaddingRightDesktop(this, _publishedValueFallback);

		///<summary>
		/// Padding Right Mobile: Spacing Padding Right Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingPaddingRightMobile")]
		public virtual string SpacingPaddingRightMobile => global::Umbraco.Cms.Web.Common.PublishedModels.PaddingSettings.GetSpacingPaddingRightMobile(this, _publishedValueFallback);

		///<summary>
		/// Padding Right Tablet: Spacing Padding Right Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingPaddingRightTablet")]
		public virtual string SpacingPaddingRightTablet => global::Umbraco.Cms.Web.Common.PublishedModels.PaddingSettings.GetSpacingPaddingRightTablet(this, _publishedValueFallback);

		///<summary>
		/// Padding Top Desktop: Spacing Padding Top Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingPaddingTopDesktop")]
		public virtual string SpacingPaddingTopDesktop => global::Umbraco.Cms.Web.Common.PublishedModels.PaddingSettings.GetSpacingPaddingTopDesktop(this, _publishedValueFallback);

		///<summary>
		/// Padding Top Mobile: Spacing Padding Top Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingPaddingTopMobile")]
		public virtual string SpacingPaddingTopMobile => global::Umbraco.Cms.Web.Common.PublishedModels.PaddingSettings.GetSpacingPaddingTopMobile(this, _publishedValueFallback);

		///<summary>
		/// Padding Top Tablet: Spacing Padding Tob Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("spacingPaddingTopTablet")]
		public virtual string SpacingPaddingTopTablet => global::Umbraco.Cms.Web.Common.PublishedModels.PaddingSettings.GetSpacingPaddingTopTablet(this, _publishedValueFallback);
	}
}
