//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "primaryButtonBorderSettings"
	/// <summary>[Nubrik][Style][Settings][Button][Primary] Border Settings</summary>
	public partial interface IPrimaryButtonBorderSettings : IPublishedElement
	{
		/// <summary>Border Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompBorderColor { get; }

		/// <summary>Border Hover Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompBorderHoverColor { get; }

		/// <summary>Border Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompBorderType { get; }

		/// <summary>Border Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompBorderWidthDesktop { get; }

		/// <summary>Border Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompBorderWidthMobile { get; }

		/// <summary>Border Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompBorderWidthTablet { get; }

		/// <summary>Radius Bottom Desktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompRadiusBottomDesktop { get; }

		/// <summary>Radius Bottom Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompRadiusBottomMobile { get; }

		/// <summary>Radius Bottom Tablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompRadiusBottomTablet { get; }

		/// <summary>Radius Left Desktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompRadiusLeftDesktop { get; }

		/// <summary>Radius Left Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompRadiusLeftMobile { get; }

		/// <summary>Radius Left Tablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompRadiusLeftTablet { get; }

		/// <summary>Radius Right Desktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompRadiusRightDesktop { get; }

		/// <summary>Radius Right Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompRadiusRightMobile { get; }

		/// <summary>Radius Right Tablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompRadiusRightTablet { get; }

		/// <summary>Radius Top Desktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompRadiusTopDesktop { get; }

		/// <summary>Radius Top Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompRadiusTopMobile { get; }

		/// <summary>Radius Top Tablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string PrimaryButtonCompRadiusTopTablet { get; }
	}

	/// <summary>[Nubrik][Style][Settings][Button][Primary] Border Settings</summary>
	[PublishedModel("primaryButtonBorderSettings")]
	public partial class PrimaryButtonBorderSettings : PublishedElementModel, IPrimaryButtonBorderSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "primaryButtonBorderSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<PrimaryButtonBorderSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public PrimaryButtonBorderSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Border Color: Primary Button Border Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompBorderColor")]
		public virtual string PrimaryButtonCompBorderColor => GetPrimaryButtonCompBorderColor(this, _publishedValueFallback);

		/// <summary>Static getter for Border Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompBorderColor(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompBorderColor");

		///<summary>
		/// Border Hover Color: Primary Button Border Hover Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompBorderHoverColor")]
		public virtual string PrimaryButtonCompBorderHoverColor => GetPrimaryButtonCompBorderHoverColor(this, _publishedValueFallback);

		/// <summary>Static getter for Border Hover Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompBorderHoverColor(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompBorderHoverColor");

		///<summary>
		/// Border Type: Primary Button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompBorderType")]
		public virtual string PrimaryButtonCompBorderType => GetPrimaryButtonCompBorderType(this, _publishedValueFallback);

		/// <summary>Static getter for Border Type</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompBorderType(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompBorderType");

		///<summary>
		/// Border Width: Primary Button Border Width Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompBorderWidthDesktop")]
		public virtual string PrimaryButtonCompBorderWidthDesktop => GetPrimaryButtonCompBorderWidthDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Border Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompBorderWidthDesktop(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompBorderWidthDesktop");

		///<summary>
		/// Border Width: Primary Button Border Width Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompBorderWidthMobile")]
		public virtual string PrimaryButtonCompBorderWidthMobile => GetPrimaryButtonCompBorderWidthMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Border Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompBorderWidthMobile(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompBorderWidthMobile");

		///<summary>
		/// Border Width: Primary Button Border Width Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompBorderWidthTablet")]
		public virtual string PrimaryButtonCompBorderWidthTablet => GetPrimaryButtonCompBorderWidthTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Border Width</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompBorderWidthTablet(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompBorderWidthTablet");

		///<summary>
		/// Radius Bottom Desktop: Primary Button Radius Bottom Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompRadiusBottomDesktop")]
		public virtual string PrimaryButtonCompRadiusBottomDesktop => GetPrimaryButtonCompRadiusBottomDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Radius Bottom Desktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompRadiusBottomDesktop(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompRadiusBottomDesktop");

		///<summary>
		/// Radius Bottom Mobile: Primary Button Radius Bottom Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompRadiusBottomMobile")]
		public virtual string PrimaryButtonCompRadiusBottomMobile => GetPrimaryButtonCompRadiusBottomMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Radius Bottom Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompRadiusBottomMobile(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompRadiusBottomMobile");

		///<summary>
		/// Radius Bottom Tablet: Primary Button Radius Bottom Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompRadiusBottomTablet")]
		public virtual string PrimaryButtonCompRadiusBottomTablet => GetPrimaryButtonCompRadiusBottomTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Radius Bottom Tablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompRadiusBottomTablet(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompRadiusBottomTablet");

		///<summary>
		/// Radius Left Desktop: Primary Button Radius Left Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompRadiusLeftDesktop")]
		public virtual string PrimaryButtonCompRadiusLeftDesktop => GetPrimaryButtonCompRadiusLeftDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Radius Left Desktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompRadiusLeftDesktop(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompRadiusLeftDesktop");

		///<summary>
		/// Radius Left Mobile: Primary Button Radius Left Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompRadiusLeftMobile")]
		public virtual string PrimaryButtonCompRadiusLeftMobile => GetPrimaryButtonCompRadiusLeftMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Radius Left Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompRadiusLeftMobile(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompRadiusLeftMobile");

		///<summary>
		/// Radius Left Tablet: Primary Button Radius Left Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompRadiusLeftTablet")]
		public virtual string PrimaryButtonCompRadiusLeftTablet => GetPrimaryButtonCompRadiusLeftTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Radius Left Tablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompRadiusLeftTablet(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompRadiusLeftTablet");

		///<summary>
		/// Radius Right Desktop: Primary Button Radius Right Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompRadiusRightDesktop")]
		public virtual string PrimaryButtonCompRadiusRightDesktop => GetPrimaryButtonCompRadiusRightDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Radius Right Desktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompRadiusRightDesktop(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompRadiusRightDesktop");

		///<summary>
		/// Radius Right Mobile: Primary Button Radius Right Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompRadiusRightMobile")]
		public virtual string PrimaryButtonCompRadiusRightMobile => GetPrimaryButtonCompRadiusRightMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Radius Right Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompRadiusRightMobile(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompRadiusRightMobile");

		///<summary>
		/// Radius Right Tablet: Primary Button Radius Right Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompRadiusRightTablet")]
		public virtual string PrimaryButtonCompRadiusRightTablet => GetPrimaryButtonCompRadiusRightTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Radius Right Tablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompRadiusRightTablet(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompRadiusRightTablet");

		///<summary>
		/// Radius Top Desktop: Primary Button Radius Top Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompRadiusTopDesktop")]
		public virtual string PrimaryButtonCompRadiusTopDesktop => GetPrimaryButtonCompRadiusTopDesktop(this, _publishedValueFallback);

		/// <summary>Static getter for Radius Top Desktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompRadiusTopDesktop(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompRadiusTopDesktop");

		///<summary>
		/// Radius Top Mobile: Primary Button Radius Top Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompRadiusTopMobile")]
		public virtual string PrimaryButtonCompRadiusTopMobile => GetPrimaryButtonCompRadiusTopMobile(this, _publishedValueFallback);

		/// <summary>Static getter for Radius Top Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompRadiusTopMobile(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompRadiusTopMobile");

		///<summary>
		/// Radius Top Tablet: Primary Button Radius Top Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryButtonCompRadiusTopTablet")]
		public virtual string PrimaryButtonCompRadiusTopTablet => GetPrimaryButtonCompRadiusTopTablet(this, _publishedValueFallback);

		/// <summary>Static getter for Radius Top Tablet</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetPrimaryButtonCompRadiusTopTablet(IPrimaryButtonBorderSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "primaryButtonCompRadiusTopTablet");
	}
}
