//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>[Nubrik][Style][Settings][Slider] Pagination Style</summary>
	[PublishedModel("sliderPaginationStyleSettings")]
	public partial class SliderPaginationStyleSettings : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "sliderPaginationStyleSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<SliderPaginationStyleSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public SliderPaginationStyleSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Active Background Color: Slider Pagination Active Background Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sliderPaginationActiveBackgroundColor")]
		public virtual string SliderPaginationActiveBackgroundColor => this.Value<string>(_publishedValueFallback, "sliderPaginationActiveBackgroundColor");

		///<summary>
		/// Background Color: Slider Pagination Background Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sliderPaginationBackgroundcolor")]
		public virtual string SliderPaginationBackgroundcolor => this.Value<string>(_publishedValueFallback, "sliderPaginationBackgroundcolor");

		///<summary>
		/// Background Hover Color: Slider Pagination Background Hover Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sliderPaginationBackgroundHoverColor")]
		public virtual string SliderPaginationBackgroundHoverColor => this.Value<string>(_publishedValueFallback, "sliderPaginationBackgroundHoverColor");

		///<summary>
		/// Height: Slider Pagination Height Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sliderPaginationHeightDesktop")]
		public virtual string SliderPaginationHeightDesktop => this.Value<string>(_publishedValueFallback, "sliderPaginationHeightDesktop");

		///<summary>
		/// Height: Slider Pagination Height Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sliderPaginationHeightMobile")]
		public virtual string SliderPaginationHeightMobile => this.Value<string>(_publishedValueFallback, "sliderPaginationHeightMobile");

		///<summary>
		/// Height: Slider Pagination Height Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sliderPaginationHeightTablet")]
		public virtual string SliderPaginationHeightTablet => this.Value<string>(_publishedValueFallback, "sliderPaginationHeightTablet");

		///<summary>
		/// Width: Slider Pagination Width Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sliderPaginationWidthDesktop")]
		public virtual string SliderPaginationWidthDesktop => this.Value<string>(_publishedValueFallback, "sliderPaginationWidthDesktop");

		///<summary>
		/// Width: Slider Pagination Width Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sliderPaginationWidthMobile")]
		public virtual string SliderPaginationWidthMobile => this.Value<string>(_publishedValueFallback, "sliderPaginationWidthMobile");

		///<summary>
		/// Width: Slider Pagination Width Tablet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sliderPaginationWidthTablet")]
		public virtual string SliderPaginationWidthTablet => this.Value<string>(_publishedValueFallback, "sliderPaginationWidthTablet");
	}
}
