//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v17.5.3+a9649da
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "tertiaryButtonBoxshadowSettings"
	/// <summary>[Nubrik][Style][Settings][Button][Tertiary] Boxshadow</summary>
	public partial interface ITertiaryButtonBoxshadowSettings : IPublishedElement
	{
		/// <summary>Blur</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string TertiaryButtonCompBorderBlur { get; }

		/// <summary>Horizontal</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string TertiaryButtonCompBorderHorizontal { get; }

		/// <summary>Position</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string TertiaryButtonCompBorderPosition { get; }

		/// <summary>Shadow Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string TertiaryButtonCompBordershadowColor { get; }

		/// <summary>Spread</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string TertiaryButtonCompBorderSpread { get; }

		/// <summary>Vertical</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string TertiaryButtonCompBorderVertical { get; }
	}

	/// <summary>[Nubrik][Style][Settings][Button][Tertiary] Boxshadow</summary>
	[PublishedModel("tertiaryButtonBoxshadowSettings")]
	public partial class TertiaryButtonBoxshadowSettings : PublishedElementModel, ITertiaryButtonBoxshadowSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const string ModelTypeAlias = "tertiaryButtonBoxshadowSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<TertiaryButtonBoxshadowSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public TertiaryButtonBoxshadowSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Blur: Tertiary Button Box Blur
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tertiaryButtonCompBorderBlur")]
		public virtual string TertiaryButtonCompBorderBlur => GetTertiaryButtonCompBorderBlur(this, _publishedValueFallback);

		/// <summary>Static getter for Blur</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetTertiaryButtonCompBorderBlur(ITertiaryButtonBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "tertiaryButtonCompBorderBlur");

		///<summary>
		/// Horizontal: Tertiary Button Box Horizontal
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tertiaryButtonCompBorderHorizontal")]
		public virtual string TertiaryButtonCompBorderHorizontal => GetTertiaryButtonCompBorderHorizontal(this, _publishedValueFallback);

		/// <summary>Static getter for Horizontal</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetTertiaryButtonCompBorderHorizontal(ITertiaryButtonBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "tertiaryButtonCompBorderHorizontal");

		///<summary>
		/// Position: Tertiary Button Box Position
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tertiaryButtonCompBorderPosition")]
		public virtual string TertiaryButtonCompBorderPosition => GetTertiaryButtonCompBorderPosition(this, _publishedValueFallback);

		/// <summary>Static getter for Position</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetTertiaryButtonCompBorderPosition(ITertiaryButtonBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "tertiaryButtonCompBorderPosition");

		///<summary>
		/// Shadow Color: Tertiary Button Box Shadow Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tertiaryButtonCompBordershadowColor")]
		public virtual string TertiaryButtonCompBordershadowColor => GetTertiaryButtonCompBordershadowColor(this, _publishedValueFallback);

		/// <summary>Static getter for Shadow Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetTertiaryButtonCompBordershadowColor(ITertiaryButtonBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "tertiaryButtonCompBordershadowColor");

		///<summary>
		/// Spread: Tertiary Button Box Spread
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tertiaryButtonCompBorderSpread")]
		public virtual string TertiaryButtonCompBorderSpread => GetTertiaryButtonCompBorderSpread(this, _publishedValueFallback);

		/// <summary>Static getter for Spread</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetTertiaryButtonCompBorderSpread(ITertiaryButtonBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "tertiaryButtonCompBorderSpread");

		///<summary>
		/// Vertical: Tertiary Button Box Vertical
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tertiaryButtonCompBorderVertical")]
		public virtual string TertiaryButtonCompBorderVertical => GetTertiaryButtonCompBorderVertical(this, _publishedValueFallback);

		/// <summary>Static getter for Vertical</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "17.5.3+a9649da")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetTertiaryButtonCompBorderVertical(ITertiaryButtonBoxshadowSettings that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "tertiaryButtonCompBorderVertical");
	}
}
