<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CompressionEnabled>false</CompressionEnabled>
    <StaticWebAssetBasePath>App_Plugins/PhasesUmbracoNeatTip</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Phases.Umbraco.NeatTip</PackageId>
    <Product>Phases.Umbraco.NeatTip</Product>
    <Title>Phases.Umbraco.NeatTip</Title>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>2.0.1</Version>
    <Authors>midhun_roy</Authors>
    <Company>Phases</Company>
    <PackageTags>umbraco-marketplace;umbraco;umbraco-v17</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <Description>NeatTip is a backoffice-only UX package for Umbraco 17. It replaces long inline property descriptions with a compact info icon next to each property label. Editors can view the full helper text on demand in an interactive tooltip — keeping the content editor clean without losing guidance.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/phases/Phases.Umbraco.NeatTip/tree/V17/V17/NeatTip/src/Phases.Umbraco.NeatTip</PackageProjectUrl>
    <RepositoryUrl>https://github.com/phases/Phases.Umbraco.NeatTip/tree/V17/V17/NeatTip/src/Phases.Umbraco.NeatTip</RepositoryUrl>
    <Copyright>Copyright © 2026 Phases</Copyright>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

	<PropertyGroup>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms.Api.Management" Version="17.2.2" />
    <PackageReference Include="Umbraco.Cms.Core" Version="17.2.2" />
    <PackageReference Include="Umbraco.Cms.Web.Common" Version="17.2.2" />
  </ItemGroup>

  <ItemGroup>
    <!-- Dont include the client folder as part of packaging nuget build -->
    <Content Remove="Client\**" />

    <!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
    <None Include="Client\public\umbraco-package.json" Pack="false" />
  </ItemGroup>

  <ItemGroup>
    <None Include="build\Phases.Umbraco.NeatTip.targets" Pack="true" PackagePath="buildTransitive\Phases.Umbraco.NeatTip.targets" />
  </ItemGroup>

  <Target Name="BuildNeatTipClient" BeforeTargets="BeforeBuild" Condition="Exists('Client\package.json')">
    <Exec Command="npm run build" WorkingDirectory="Client" />
  </Target>

  <ItemGroup>
    <None Update="icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
